const assert = require("node:assert/strict");
const api = require("./dados-gerenciais-relatorio");
const registro = (id, colaborador, horas, obra = "FIOCRUZ", projeto = "Elétrico Baixa Tensão", status = "Finalizado") => ({ id, colaborador, horas, obraCodigo: "OBR-000015", obra, projeto, etapa: id, status });
const dados = api.construirDadosGerenciaisRelatorio([registro("a", "Bruno", 25.85), registro("b", "Geovanna", 24.83), registro("c", "Hellen", 24.38), registro("d", "Rodrigo", 14.28, "MATERNIDADE", "SPDA", "Em progresso")]);
assert.deepEqual(dados.horasPorColaborador.map((x) => x.label), ["Bruno", "Geovanna", "Hellen", "Rodrigo"]);
assert.deepEqual(dados.horasPorColaborador.map((x) => x.valor), [25.85, 24.83, 24.38, 14.28]);
assert.deepEqual(dados.atividadesPorColaborador.map((x) => x.valor), [1, 1, 1, 1]);
assert.equal(api.formatarLabelFrenteRelatorio("OBR-000015 — FIOCRUZ — Elétrico Baixa Tensão"), "FIOCRUZ · Elétrico BT");
assert.equal(dados.percentualFinalizadas, 75);
assert.deepEqual(dados.statusLegenda.map((x) => x.label), ["Em progresso", "Finalizado"]);
assert.equal(dados.status.length, 4);
const dezenove = api.construirDadosGerenciaisRelatorio(Array.from({ length: 19 }, (_, i) => registro(`s${i}`, "Equipe", 1, "Obra", "SPDA", i === 18 ? "Em progresso" : "Finalizado")));
assert.equal(dezenove.percentualFinalizadas, 95);
const treze = Array.from({ length: 13 }, (_, i) => registro(`top${i}`, "Pessoa", i + 17, `Obra ${i}`, "SPDA"));
const top = api.construirDadosGerenciaisRelatorio(treze).topHorasPorFrente;
assert.equal(top.length, 10); assert.ok(top.every((x, i) => !i || top[i - 1].valor >= x.valor));
console.log("Dados gerenciais: consistência, ordem, Top 10, labels e status validados");