const assert = require("node:assert/strict");
const { fases, projetosComFaseItem, itensPorFase, projetoExigeFaseItem, valorFinal, valorFinalMultiplos, separarItens, prepararEdicao } = require("./fase-item");

assert.deepEqual(fases, ["Lançamento", "Distribuição", "Plotagem", "Estudos", "Compatibilização", "Outros"]);
assert.deepEqual(itensPorFase.Distribuição, ["Eletrocalha", "Leito", "Perfilado", "Eletroduto Flexível", "Eletroduto FG", "Cabo PP", "Outros"]);
assert.ok(itensPorFase.Estudos.includes("NBR-5410"));
assert.ok(itensPorFase.Compatibilização.includes("Arquitetura"));
assert.deepEqual(projetosComFaseItem, ["CFTV", "Cabeamento", "Telefonia", "Elétrico Baixa Tensão", "Iluminação Externa", "SPDA", "Subestação", "Alimentador", "Mapa Chave/Situação", "Sonorização", "Solar", "Automação", "Lógica", "Média Tensão"]);
projetosComFaseItem.forEach((projeto) => assert.equal(projetoExigeFaseItem(projeto), true));
["", "Site", "Todos", "Outros", "Projeto personalizado"].forEach((projeto) => assert.equal(projetoExigeFaseItem(projeto), false));
assert.equal(valorFinal("Distribuição", ""), "Distribuição");
assert.equal(valorFinal("Outros", "  Levantamento  "), "Levantamento");
assert.equal(valorFinal("Outros", "  Canaleta  "), "Canaleta");
assert.equal(valorFinalMultiplos(["Eletrocalha", "Leito"], ""), "Eletrocalha · Leito");
assert.equal(valorFinalMultiplos(["Eletrocalha", "Outros"], " Canaleta "), "Eletrocalha · Canaleta");
assert.deepEqual(separarItens("Eletrocalha · Leito"), ["Eletrocalha", "Leito"]);
assert.deepEqual(prepararEdicao("Distribuição", "Eletrocalha"), { faseSelecionada: "Distribuição", faseOutro: "", itensSelecionados: ["Eletrocalha"], itemOutro: "", itensDisponiveis: itensPorFase.Distribuição });
assert.deepEqual(prepararEdicao("Distribuição", "Eletrocalha · Leito · Canaleta"), { faseSelecionada: "Distribuição", faseOutro: "", itensSelecionados: ["Eletrocalha", "Leito", "Outros"], itemOutro: "Canaleta", itensDisponiveis: itensPorFase.Distribuição });
assert.deepEqual(prepararEdicao("Levantamento", "Conferência existente"), { faseSelecionada: "Outros", faseOutro: "Levantamento", itensSelecionados: ["Outros"], itemOutro: "Conferência existente", itensDisponiveis: itensPorFase.Outros });
assert.deepEqual(prepararEdicao(null, null), { faseSelecionada: "", faseOutro: "", itensSelecionados: [], itemOutro: "", itensDisponiveis: [] });
console.log("Testes de Fase e Item das atividades: OK");
