(function () {
  "use strict";
  const el = (id) => document.getElementById(id);
  const menu = el("relatoriosOpcoes"), menuButton = el("btnRelatorios"), abrir = el("btnAbrirRelatorioObra"), modal = el("relatorioObraModal"), form = el("relatorioObraForm"), select = el("relatorioObraSelect"), status = el("relatorioObraStatus"), preview = el("relatorioObraPreview"), checks = el("relatorioObraPendencias"), historico = el("relatorioObraHistorico"), disciplinas = el("relatorioObraDisciplinas"), tbody = el("relatorioObraDisciplinasBody"), revisao = el("relatorioObraRevisao"), entregaId = el("relatorioObraEntregaId");
  let analiseAtual = null;
  const h = (v) => String(v ?? "").replace(/[<>&"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c]));
  const numero = (v) => Number(v || 0).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  async function json(response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Não foi possível concluir a operação."); return data; }
  function fechar() { modal.hidden = true; menu.hidden = true; menuButton.setAttribute("aria-expanded", "false"); }
  async function carregarObras() { const obras = await fetch("/api/obras-admin").then(json); select.innerHTML = '<option value="">Selecione uma obra</option>' + obras.map((o) => `<option value="${h(o.id)}">${h(o.codigo)} — ${h(o.nome)}</option>`).join(""); }
  function renderizar(data) {
    analiseAtual = data; const r = data.resumo;
    preview.hidden = false; preview.innerHTML = `<h3>${h(data.obra.codigo)} — ${h(data.obra.nome)}</h3><dl><div><dt>Período</dt><dd>${h(data.periodo.texto)}</dd></div><div><dt>Disciplinas</dt><dd>${r.disciplinas}</dd></div><div><dt>Atividades consolidadas</dt><dd>${r.atividades}</dd></div><div><dt>Lançamentos</dt><dd>${r.lancamentos}</dd></div><div><dt>Horas</dt><dd>${numero(r.horasTotais)} h</dd></div><div><dt>Colaboradores</dt><dd>${r.colaboradores}</dd></div><div><dt>Pendências</dt><dd>${r.pendencias}</dd></div></dl>`;
    disciplinas.hidden = false; tbody.innerHTML = data.disciplinas.map((d) => `<tr data-chave="${h(d.projetoChave)}"><td>${h(d.projeto)}${d.situacao === "Sem atividade registrada" ? '<small class="delivery-warning">Sem atividade registrada</small>' : ""}</td><td><select data-campo="tipo"><option value="entrega_inicial">Entrega inicial</option><option value="revisao" selected>Revisão</option></select></td><td><input data-campo="revisao" value="${h(d.revisao || revisao.value)}" required></td><td>${numero(d.horas)} h</td><td>${d.atividades}</td><td><input type="url" data-campo="link" pattern="https?://.*" value="${h(d.linkProjeto)}" placeholder="https://..."></td></tr>`).join("");
    checks.hidden = false; checks.innerHTML = `<h3>Verificação de encerramento</h3><p class="delivery-ok">✓ ${r.disciplinas} disciplinas identificadas</p><p class="delivery-ok">✓ ${r.atividades} atividades consolidadas</p>${data.pendencias.length ? data.pendencias.map((p) => `<p class="delivery-warning">⚠ ${h(p.mensagem)}</p>`).join("") : '<p class="delivery-ok">✓ Nenhuma pendência interna impeditiva identificada</p>'}`;
    historico.hidden = false; historico.innerHTML = `<h3>Histórico de entregas</h3>${data.historico.length ? [...data.historico].reverse().map((e) => `<article><strong>${h(e.revisao)} — ${h(String(e.data_entrega).split("-").reverse().join("/"))}</strong><span><button type="button" data-ver-entrega="${h(e.id)}">Ver dados / Editar</button><button type="button" data-regenerar="${h(e.id)}">Regenerar relatório</button></span></article>`).join("") : "<p>Nenhuma entrega registrada.</p>"}`;
  }
  async function carregarObra(id, idEntrega = "") { status.textContent = "Buscando todo o histórico da obra..."; const data = await fetch(`/api/obra-entregas?obraId=${encodeURIComponent(id)}${idEntrega ? `&entregaId=${encodeURIComponent(idEntrega)}` : ""}`).then(json); renderizar(data); if (data.entrega) { const e = data.entrega; entregaId.value = e.id; el("relatorioObraData").value = e.data_entrega; revisao.value = e.revisao; el("relatorioObraLink").value = e.link_processo; el("relatorioObraObservacoes").value = e.observacoes || ""; form.querySelector(`[name="relatorioObraTipo"][value="${e.tipo_emissao}"]`).checked = true; } else { entregaId.value = ""; revisao.value = data.proximaRevisao || "REV00"; } status.textContent = ""; }
  function projetosPayload() { return [...tbody.querySelectorAll("tr")].map((tr) => ({ projetoChave: tr.dataset.chave, tipoEmissao: tr.querySelector('[data-campo="tipo"]').value, revisao: tr.querySelector('[data-campo="revisao"]').value.trim(), linkProjeto: tr.querySelector('[data-campo="link"]').value.trim() })); }
  async function baixar(obraId, id) { const response = await fetch("/api/gerar-relatorio-obra-word", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ obraId, entregaId: id }) }); if (!response.ok) { const e = await response.json().catch(() => ({})); throw new Error(e.error || "Falha ao gerar o Word."); } const blob = await response.blob(), url = URL.createObjectURL(blob), a = document.createElement("a"); a.href = url; const disposition = response.headers.get("Content-Disposition") || ""; a.download = disposition.match(/filename="([^"]+)"/)?.[1] || "relatorio-entrega-obra.docx"; a.click(); URL.revokeObjectURL(url); }
  menuButton?.addEventListener("click", () => { menu.hidden = !menu.hidden; menuButton.setAttribute("aria-expanded", String(!menu.hidden)); });
  abrir?.addEventListener("click", async () => { modal.hidden = false; menu.hidden = true; el("relatorioObraData").value ||= new Date().toISOString().slice(0, 10); status.textContent = "Carregando obras..."; try { await carregarObras(); status.textContent = ""; } catch (e) { status.textContent = e.message; } });
  [el("btnFecharRelatorioObra"), el("btnCancelarRelatorioObra")].forEach((b) => b?.addEventListener("click", fechar));
  select?.addEventListener("change", () => select.value && carregarObra(select.value).catch((e) => status.textContent = e.message));
  form?.querySelectorAll('[name="relatorioObraTipo"]').forEach((radio) => radio.addEventListener("change", () => { if (radio.checked && radio.value === "entrega_inicial" && !entregaId.value) revisao.value = "REV00"; else if (radio.checked && analiseAtual?.proximaRevisao) revisao.value = analiseAtual.proximaRevisao; }));
  el("btnAplicarRevisaoDisciplinas")?.addEventListener("click", () => tbody.querySelectorAll('[data-campo="revisao"]').forEach((input) => input.value = revisao.value));
  historico?.addEventListener("click", (event) => { const editar = event.target.closest("[data-ver-entrega]"), regenerar = event.target.closest("[data-regenerar]"); if (editar) carregarObra(select.value, editar.dataset.verEntrega).catch((e) => status.textContent = e.message); if (regenerar) baixar(select.value, regenerar.dataset.regenerar).catch((e) => status.textContent = e.message); });
  form?.addEventListener("submit", async (event) => { event.preventDefault(); if (!analiseAtual) return; if (analiseAtual.pendencias.length && !confirm(`Há ${analiseAtual.pendencias.length} pendência(s). Deseja gerar mesmo assim?`)) return; const botao = el("btnSalvarGerarRelatorioObra"); botao.disabled = true; status.textContent = "Salvando o snapshot da entrega..."; try { const payload = { obraId: select.value, entregaId: entregaId.value, dataEntrega: el("relatorioObraData").value, tipoEmissao: form.querySelector('[name="relatorioObraTipo"]:checked').value, revisao: revisao.value.trim(), linkProcesso: el("relatorioObraLink").value.trim(), observacoes: el("relatorioObraObservacoes").value.trim(), projetos: projetosPayload() }; const method = entregaId.value ? "PATCH" : "POST"; const salvo = await fetch("/api/obra-entregas", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }).then(json); entregaId.value = salvo.entrega.id; status.textContent = "Gerando documento Word..."; await baixar(select.value, salvo.entrega.id); status.textContent = "Entrega salva e relatório gerado."; await carregarObra(select.value, salvo.entrega.id); } catch (e) { status.textContent = e.message; } finally { botao.disabled = false; } });
})();