(function () {
  "use strict";
  const el = (id) => document.getElementById(id);
  const menu = el("relatoriosOpcoes"), menuButton = el("btnRelatorios"), abrir = el("btnAbrirRelatorioObra"), modal = el("relatorioObraModal"), form = el("relatorioObraForm"), select = el("relatorioObraSelect"), status = el("relatorioObraStatus"), preview = el("relatorioObraPreview"), checks = el("relatorioObraPendencias"), historico = el("relatorioObraHistorico"), disciplinas = el("relatorioObraDisciplinas"), tbody = el("relatorioObraDisciplinasBody"), revisao = el("relatorioObraRevisao"), entregaId = el("relatorioObraEntregaId"), inicio = el("relatorioObraPeriodoInicio"), fim = el("relatorioObraPeriodoFim"), atividadesBody = el("relatorioObraAtividadesBody"), atividadesSecao = el("relatorioObraAtividades"), tabs = el("relatorioObraTabs");
  let analiseAtual = null, filtroAtividade = "todos", idsFiltrados = null, abaAtual = "resumo", carregamento = 0;
  const h = (v) => String(v ?? "").replace(/[<>&"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c]));
  const normal = (v) => String(v || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().trim();
  const numero = (v) => Number(v || 0).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const dataBr = (v) => v ? String(v).slice(0, 10).split("-").reverse().join("/") : "—";
  async function json(response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || data.mensagem || "Não foi possível concluir a operação."); return data; }
  function fechar() { modal.hidden = true; menu.hidden = true; menuButton.setAttribute("aria-expanded", "false"); document.body.classList.remove("delivery-report-open"); }
  async function carregarObras() { const obras = await fetch("/api/obras-admin").then(json); select.innerHTML = '<option value="">Selecione uma obra</option>' + obras.map((o) => `<option value="${h(o.id)}">${h(o.codigo)} — ${h(o.nome)}</option>`).join(""); }
  function abrirAba(nome) { abaAtual = nome; tabs.querySelectorAll("button").forEach((b) => b.classList.toggle("active", b.dataset.tab === nome)); form.querySelectorAll("[data-panel]").forEach((p) => { p.hidden = p.dataset.panel !== nome; }); }
  function classificacaoTexto(a) { return (a.classificacoes || []).map((c) => `${c.fase} / ${c.item}`).join("; ") || "—"; }
  function atividadesFiltradas() { return (analiseAtual?.atividades || []).filter((a) => { if (idsFiltrados && !idsFiltrados.has(String(a.id))) return false; const s = normal(a.status); if (filtroAtividade === "nao-finalizados") return s !== "finalizado"; return filtroAtividade === "todos" || s === filtroAtividade; }); }
  function renderizarAtividades() {
    const lista = atividadesFiltradas(); el("relatorioObraAtividadesContagem").textContent = `${lista.length} de ${analiseAtual?.atividades?.length || 0}`;
    atividadesBody.innerHTML = lista.length ? lista.map((a) => `<tr><td>${h(dataBr(a.dataTermino || a.dataInicio))}</td><td>${h(a.colaborador || "—")}</td><td>${h(a.projeto || "—")}</td><td><span class="delivery-ellipsis" title="${h(a.trabalhos)}">${h(a.trabalhos || "—")}</span></td><td><span class="delivery-ellipsis" title="${h(classificacaoTexto(a))}">${h(classificacaoTexto(a))}</span></td><td>${numero(a.horas)} h</td><td><span class="delivery-status">${h(a.status || "—")}</span></td><td>${normal(a.status) !== "finalizado" ? `<button type="button" class="secondary delivery-finish" data-finalizar="${h(a.id)}">Finalizar</button>` : "—"}</td></tr>`).join("") : '<tr><td colspan="8" class="empty">Nenhuma atividade encontrada neste filtro.</td></tr>';
  }
  function renderizar(data) {
    analiseAtual = data; const r = data.resumo; tabs.hidden = false;
    preview.innerHTML = `<h3>${h(data.obra.codigo)} — ${h(data.obra.nome)}</h3><p>Período desta entrega: <strong>${h(data.periodoEntrega.texto)}</strong></p><p>Histórico completo: ${h(data.periodoHistorico.texto)}</p><dl><div><dt>Disciplinas</dt><dd>${r.disciplinas}</dd></div><div><dt>Atividades consolidadas</dt><dd>${r.atividades}</dd></div><div><dt>Lançamentos</dt><dd>${r.lancamentos}</dd></div><div><dt>Horas</dt><dd>${numero(r.horasTotais)} h</dd></div><div><dt>Colaboradores</dt><dd>${r.colaboradores}</dd></div><div><dt>Pendências</dt><dd>${r.pendencias}</dd></div></dl>`;
    tbody.innerHTML = data.disciplinas.map((d) => `<tr data-chave="${h(d.projetoChave)}"><td>${h(d.projeto)}<small class="${d.situacao === "Entregue" ? "delivery-ok" : "delivery-warning"}">${h(d.situacao)}</small></td><td><select data-campo="tipo"><option value="entrega_inicial">Entrega inicial</option><option value="revisao" selected>Revisão</option></select></td><td><input data-campo="revisao" value="${h(d.revisao || revisao.value)}" required></td><td>${numero(d.horas)} h</td><td>${d.atividades}</td><td><input type="url" data-campo="link" pattern="https?://.*" value="${h(d.linkProjeto)}" placeholder="https://..."></td></tr>`).join("");
    const acao = (p) => `<button type="button" class="secondary" data-ver-pendencia="${h(p.tipo)}" data-status="${h(normal(p.status))}" data-ids="${h((p.atividadeIds || []).join(","))}">Ver atividades</button>`;
    checks.innerHTML = `<h3>Verificação de encerramento</h3><p class="delivery-ok">✓ ${r.atividades} atividades consolidadas no período</p>${data.pendencias.length ? data.pendencias.map((p) => `<div class="delivery-check-row"><span class="delivery-warning">⚠ ${h(p.mensagem)}</span>${p.tipo === "status" || p.atividadeIds?.length ? acao(p) : ""}</div>`).join("") : '<p class="delivery-ok">✓ Nenhuma pendência interna impeditiva identificada</p>'}`;
    historico.innerHTML = `<h3>Histórico de entregas</h3>${data.historico.length ? [...data.historico].reverse().map((e) => `<article><strong>${h(e.revisao)} — ${h(dataBr(e.data_entrega))}</strong><small>${h(dataBr(e.periodo_inicio))} a ${h(dataBr(e.periodo_fim))}</small><span><button type="button" data-ver-entrega="${h(e.id)}">Ver dados / Editar</button><button type="button" data-regenerar="${h(e.id)}">Gerar relatório novamente</button><button type="button" class="delivery-delete" data-apagar-entrega="${h(e.id)}" data-revisao="${h(e.revisao)}">Apagar revisão</button></span></article>`).join("") : "<p>Nenhuma entrega registrada.</p>"}`;
    el("relatorioObraPeriodoHistorico").textContent = `Histórico completo da obra: ${dataBr(data.periodoHistorico.inicio)} a ${dataBr(data.periodoHistorico.fim)}`;
    [preview, disciplinas, atividadesSecao, checks, historico].forEach((x) => x.hidden = false); renderizarAtividades(); abrirAba(abaAtual);
  }
  async function carregarObra(id, idEntrega = "", periodo = null) {
    const token = ++carregamento; status.textContent = "Atualizando dados...";
    const query = new URLSearchParams({ obraId: id }); if (idEntrega) query.set("entregaId", idEntrega); if (periodo?.inicio) query.set("periodoInicio", periodo.inicio); if (periodo?.fim) query.set("periodoFim", periodo.fim);
    const data = await fetch(`/api/obra-entregas?${query}`).then(json); if (token !== carregamento) return;
    renderizar(data);
    if (data.entrega) { const e = data.entrega; entregaId.value = e.id; el("relatorioObraData").value = e.data_entrega; revisao.value = e.revisao; el("relatorioObraLink").value = e.link_processo; el("relatorioObraObservacoes").value = e.observacoes || ""; inicio.value = e.periodo_inicio || data.periodoEntrega.inicio; fim.value = e.periodo_fim || data.periodoEntrega.fim; form.querySelector(`[name="relatorioObraTipo"][value="${e.tipo_emissao}"]`).checked = true; }
    else { entregaId.value = ""; revisao.value = data.proximaRevisao || "REV00"; inicio.value = periodo?.inicio || data.periodoHistorico.inicio; fim.value = periodo?.fim || data.periodoHistorico.fim; }
    status.textContent = "";
  }
  function projetosPayload() { return [...tbody.querySelectorAll("tr")].map((tr) => ({ projetoChave: tr.dataset.chave, tipoEmissao: tr.querySelector('[data-campo="tipo"]').value, revisao: tr.querySelector('[data-campo="revisao"]').value.trim(), linkProjeto: tr.querySelector('[data-campo="link"]').value.trim() })); }
  async function baixar(obraId, id) { const response = await fetch("/api/gerar-relatorio-obra-word", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ obraId, entregaId: id }) }); if (!response.ok) { const e = await response.json().catch(() => ({})); throw new Error(e.error || "Falha ao gerar o Word."); } const blob = await response.blob(), url = URL.createObjectURL(blob), a = document.createElement("a"); a.href = url; a.download = (response.headers.get("Content-Disposition") || "").match(/filename="([^"]+)"/)?.[1] || "relatorio-entrega-obra.docx"; a.click(); URL.revokeObjectURL(url); }
  menuButton?.addEventListener("click", () => { menu.hidden = !menu.hidden; menuButton.setAttribute("aria-expanded", String(!menu.hidden)); });
  abrir?.addEventListener("click", async () => { modal.hidden = false; menu.hidden = true; document.body.classList.add("delivery-report-open"); el("relatorioObraData").value ||= new Date().toISOString().slice(0, 10); status.textContent = "Carregando obras..."; try { await carregarObras(); status.textContent = ""; } catch (e) { status.textContent = e.message; } });
  [el("btnFecharRelatorioObra"), el("btnCancelarRelatorioObra")].forEach((b) => b?.addEventListener("click", fechar));
  select?.addEventListener("change", () => select.value && carregarObra(select.value).catch((e) => status.textContent = e.message));
  el("btnAtualizarPeriodo")?.addEventListener("click", () => carregarObra(select.value, entregaId.value, { inicio: inicio.value, fim: fim.value }).catch((e) => status.textContent = e.message));
  el("btnPeriodoCompleto")?.addEventListener("click", () => { inicio.value = analiseAtual?.periodoHistorico.inicio || ""; fim.value = analiseAtual?.periodoHistorico.fim || ""; carregarObra(select.value, entregaId.value, { inicio: inicio.value, fim: fim.value }).catch((e) => status.textContent = e.message); });
  tabs?.addEventListener("click", (e) => { const b = e.target.closest("[data-tab]"); if (b) abrirAba(b.dataset.tab); });
  el("relatorioObraAtividades")?.addEventListener("click", async (e) => { const filtro = e.target.closest("[data-activity-filter]"); if (filtro) { filtroAtividade = filtro.dataset.activityFilter; idsFiltrados = null; atividadesSecao.querySelectorAll("[data-activity-filter]").forEach((b) => b.classList.toggle("active", b === filtro)); renderizarAtividades(); return; } const finalizar = e.target.closest("[data-finalizar]"); if (!finalizar || !confirm("Deseja finalizar esta atividade?")) return; finalizar.disabled = true; status.textContent = "Finalizando e sincronizando atividade..."; try { await fetch("/api/atividades", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ acao: "finalizarAtividade", id: finalizar.dataset.finalizar }) }).then(json); await carregarObra(select.value, entregaId.value, { inicio: inicio.value, fim: fim.value }); abrirAba("atividades"); } catch (err) { status.textContent = err.message; finalizar.disabled = false; } });
  checks?.addEventListener("click", (e) => { const b = e.target.closest("[data-ver-pendencia]"); if (!b) return; const tipo = b.dataset.verPendencia; filtroAtividade = tipo === "status" ? b.dataset.status : "todos"; idsFiltrados = b.dataset.ids ? new Set(b.dataset.ids.split(",")) : null; renderizarAtividades(); abrirAba("atividades"); });
  form?.querySelectorAll('[name="relatorioObraTipo"]').forEach((radio) => radio.addEventListener("change", () => { if (radio.checked && radio.value === "entrega_inicial" && !entregaId.value) revisao.value = "REV00"; else if (radio.checked && analiseAtual?.proximaRevisao) revisao.value = analiseAtual.proximaRevisao; }));
  el("btnAplicarRevisaoDisciplinas")?.addEventListener("click", () => tbody.querySelectorAll('[data-campo="revisao"]').forEach((input) => input.value = revisao.value));
  historico?.addEventListener("click", async (event) => {
    const editar = event.target.closest("[data-ver-entrega]"), regenerar = event.target.closest("[data-regenerar]"), apagar = event.target.closest("[data-apagar-entrega]");
    if (editar) carregarObra(select.value, editar.dataset.verEntrega).catch((e) => status.textContent = e.message);
    if (regenerar) { regenerar.disabled = true; status.textContent = "Gerando relatório novamente..."; try { await baixar(select.value, regenerar.dataset.regenerar); status.textContent = "Relatório gerado novamente."; } catch (e) { status.textContent = e.message; } finally { regenerar.disabled = false; } }
    if (apagar && confirm(`Deseja apagar definitivamente a revisão ${apagar.dataset.revisao}? Esta ação não pode ser desfeita.`)) { apagar.disabled = true; status.textContent = "Apagando revisão..."; try { await fetch("/api/obra-entregas", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ obraId: select.value, entregaId: apagar.dataset.apagarEntrega }) }).then(json); await carregarObra(select.value); status.textContent = "Revisão apagada com sucesso."; } catch (e) { status.textContent = e.message; apagar.disabled = false; } }
  });
  form?.addEventListener("submit", async (event) => { event.preventDefault(); if (!analiseAtual) return; if (analiseAtual.pendencias.length && !confirm(`Há ${analiseAtual.pendencias.length} grupo(s) de pendências. Deseja gerar mesmo assim?`)) return; const botao = el("btnSalvarGerarRelatorioObra"); botao.disabled = true; status.textContent = "Salvando o snapshot da entrega..."; try { const payload = { obraId: select.value, entregaId: entregaId.value, dataEntrega: el("relatorioObraData").value, periodoInicio: inicio.value, periodoFim: fim.value, tipoEmissao: form.querySelector('[name="relatorioObraTipo"]:checked').value, revisao: revisao.value.trim(), linkProcesso: el("relatorioObraLink").value.trim(), observacoes: el("relatorioObraObservacoes").value.trim(), projetos: projetosPayload() }; const salvo = await fetch("/api/obra-entregas", { method: entregaId.value ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }).then(json); entregaId.value = salvo.entrega.id; status.textContent = "Gerando documento Word..."; await baixar(select.value, salvo.entrega.id); await carregarObra(select.value, salvo.entrega.id); status.textContent = "Entrega salva e relatório gerado."; } catch (e) { status.textContent = e.message; } finally { botao.disabled = false; } });
})();