import { adjacentClashIndex, filterClashResults, groupClashResults, serializeClashViewpoint } from "./clash-core.js";
import { runXktClashAnalysis } from "./clash-api.js";
import { extractEntityGeometry } from "./xkt-geometry.js";

const STATUS_LABELS={new:"Novo",reviewing:"Em análise",accepted:"Aceito",resolved:"Resolvido",ignored:"Ignorado"};
let sdkPromise; const loadBCFSDK=()=>sdkPromise||=import("https://cdn.jsdelivr.net/npm/@xeokit/xeokit-sdk@2.6.107/dist/xeokit-sdk.min.es.js");
function download(name,content,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);}

export function createClashFeature({viewer,panel,models,transforms,getAllObjectIds,requestRenderFrame,jsPDF,xktLoader}) {
 let results=[],visibleResults=[],activeIndex=-1,marker=null,bcfPlugin=null,isolated=false,controller=null;
 panel.innerHTML=`<div class="collision-panel-header"><div><div class="collision-panel-title">⚡ Compatibilização BIM</div><div class="collision-panel-subtitle">Análise geométrica entre modelos XKT</div></div><button id="closeCollisionPanel">✕</button></div>
 <label class="collision-label">Preset<select id="clashPreset"><option value="">Seleção manual</option><option value="IFC_EST|IFC_HID">Estrutura × Hidráulica</option><option value="IFC_EST|IFC_ELE">Estrutura × Elétrica</option><option value="IFC_EST|IFC_CLI">Estrutura × Climatização</option><option value="IFC_ARQ|IFC_HID">Arquitetura × Instalações</option></select></label>
 <div class="clash-groups"><label class="collision-label">Grupo A<select id="collisionModelA"></select></label><span>×</span><label class="collision-label">Grupo B<select id="collisionModelB"></select></label></div>
 <label class="collision-label">Tipo<select id="clashMode"><option value="intersection">Interferência física</option><option value="clearance">Proximidade / Folga</option></select></label><label id="clashDistanceLabel" class="collision-label">Precisão geométrica (m)<input id="collisionRadius" type="number" min="0.000001" max="1" step="0.001" value="0.001"></label>
 <div class="collision-actions"><button id="runCollisionCheck">Executar análise</button><button id="cancelCollisionCheck" hidden>Cancelar</button></div><p id="collisionSummary" class="collision-summary" role="status">Selecione dois modelos XKT.</p>
 <div class="clash-filters"><input id="clashSearch" type="search" placeholder="Buscar nome, ID, classe ou modelo"><select id="clashStatus"><option value="pending">Pendentes</option><option value="all">Todos os status</option><option value="resolved">Resolvidos</option></select></div><div id="clashNavigation" class="clash-navigation" hidden><button data-nav="-1">←</button><strong id="clashCounter">0 / 0</strong><button data-nav="1">→</button></div><div id="clashDetail"></div><div id="collisionResults" class="collision-results"></div><div class="collision-actions"><button id="downloadCollisionPdf" disabled>Baixar PDF</button><button id="exportAllBcf" disabled>Exportar viewpoints</button></div>`;
 const $=s=>panel.querySelector(s), setA=$("#collisionModelA"),setB=$("#collisionModelB"),summary=$("#collisionSummary");
 const optionModels=models().filter(m=>m.src).map(m=>({...m,transform:transforms()[m.id]||m.transform||{}}));
 optionModels.forEach(model=>[setA,setB].forEach(select=>{const o=document.createElement("option");o.value=model.id;o.textContent=model.label||model.id;select.append(o);})); if(setB.options.length>1)setB.selectedIndex=1;
 const selected=s=>optionModels.find(m=>m.id===s.value);
 const sceneIds=c=>[c.objectA.objectId,c.objectB.objectId].map((id,i)=>viewer.scene.objects[id]?id:Object.keys(viewer.scene.objects).find(key=>key.endsWith(`#${id}`)||key.endsWith(`.${id}`))||null);
 const restore=()=>{const ids=getAllObjectIds();viewer.scene.setObjectsVisible(ids,true);viewer.scene.setObjectsXRayed(ids,false);viewer.scene.setObjectsHighlighted(ids,false);viewer.scene.setObjectsSelected(ids,false);isolated=false;marker?.destroy?.();marker=null;requestRenderFrame();};
 async function showClash(index,mode="focus"){if(!visibleResults.length)return;activeIndex=Math.max(0,Math.min(index,visibleResults.length-1));const clash=visibleResults[activeIndex],ids=sceneIds(clash),valid=ids.filter(Boolean);restore();viewer.scene.setObjectsHighlighted(ids[0]?[ids[0]]:[],true);viewer.scene.setObjectsSelected(ids[1]?[ids[1]]:[],true);if(mode==="isolate"){viewer.scene.setObjectsVisible(getAllObjectIds(),false);viewer.scene.setObjectsVisible(valid,true);isolated=true;}if(mode==="context"){viewer.scene.setObjectsXRayed(getAllObjectIds(),true);viewer.scene.setObjectsXRayed(valid,false);}if(valid.length)viewer.cameraFlight.flyTo({aabb:viewer.scene.getAABB(valid),duration:.6});const {Marker}=await loadBCFSDK();marker=new Marker(viewer.scene,{worldPos:clash.position,occludable:true});render();requestRenderFrame();}
 async function exportViewpoint(clash){const {BCFViewpointsPlugin}=await loadBCFSDK();bcfPlugin||=new BCFViewpointsPlugin(viewer);download(`${clash.id}.bcfv`,JSON.stringify(serializeClashViewpoint(clash,bcfPlugin.getViewpoint({spacesVisible:false,openingsVisible:false})),null,2),"application/json");}
 function applyFilters(){const mode=$("#clashStatus").value,statuses=mode==="all"?Object.keys(STATUS_LABELS):mode==="resolved"?["resolved"]:["new","reviewing","accepted"];visibleResults=filterClashResults(results,{query:$("#clashSearch").value,statuses});activeIndex=visibleResults.length?Math.min(Math.max(activeIndex,0),visibleResults.length-1):-1;render();}
 function render(){const list=$("#collisionResults");list.innerHTML="";for(const [label,clashes] of groupClashResults(visibleResults)){const group=document.createElement("details");group.open=true;group.innerHTML=`<summary>${label} — ${clashes.length}</summary>`;clashes.forEach(c=>{const b=document.createElement("button");b.className="collision-result-item";b.textContent=`${c.objectA.type} × ${c.objectB.type} • ${STATUS_LABELS[c.status]}`;b.onclick=()=>showClash(visibleResults.indexOf(c));group.append(b);});list.append(group);}if(!visibleResults.length)list.textContent=results.length?"Nenhum resultado corresponde aos filtros.":"✓ Nenhuma interferência encontrada";$("#clashNavigation").hidden=!visibleResults.length;$("#clashCounter").textContent=`${activeIndex+1} / ${visibleResults.length}`;$("#downloadCollisionPdf").disabled=$("#exportAllBcf").disabled=!results.length;const c=visibleResults[activeIndex],d=$("#clashDetail");d.innerHTML=c?`<article class="clash-detail"><b>Interferência ${activeIndex+1} de ${visibleResults.length}</b><p>${c.objectA.name}<br><small>${c.objectA.type} • ${c.objectA.originalSystemId||c.objectA.objectId}</small></p><div>×</div><p>${c.objectB.name}<br><small>${c.objectB.type} • ${c.objectB.originalSystemId||c.objectB.objectId}</small></p><p>Interseção física confirmada</p><div class="collision-actions"><button data-action="focus">Visualizar</button><button data-action="isolate">Isolar</button><button data-action="context">Contexto</button><button data-action="bcf">BCF Viewpoint</button></div><label>Status <select data-action="status">${Object.entries(STATUS_LABELS).map(([v,l])=>`<option value="${v}"${c.status===v?" selected":""}>${l}</option>`).join("")}</select></label></article>`:"";["focus","isolate","context"].forEach(a=>d.querySelector(`[data-action="${a}"]`)?.addEventListener("click",()=>showClash(activeIndex,a)));d.querySelector('[data-action="bcf"]')?.addEventListener("click",()=>exportViewpoint(c));d.querySelector('[data-action="status"]')?.addEventListener("change",e=>{c.status=e.target.value;applyFilters();});}
 async function prepare(model){summary.textContent="Preparando objetos...";const extract=entities=>entities.map(e=>extractEntityGeometry(e,{modelId:model.id,transform:model.transform,metaObjects:viewer.metaScene?.metaObjects||{}})).filter(Boolean).map(o=>({...o,id:o.objectId}));const loaded=Object.values(viewer.scene.objects).filter(e=>e.model?.id===model.id||e.id.startsWith(`${model.id}#`));const available=extract(loaded);if(available.length)return available;const analysisId=`__clash_${model.id}_${Date.now()}`;let analysisModel=xktLoader.load({id:analysisId,src:model.src,globalizeObjectIds:true,readableGeometryEnabled:true,visible:false,edges:false,saoEnabled:false,dtxEnabled:false});await new Promise((resolve,reject)=>{analysisModel.on("loaded",resolve);analysisModel.on("error",reject);});if(model.transform.position)analysisModel.position=[...model.transform.position];if(model.transform.rotation)analysisModel.rotation=[...model.transform.rotation];await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));const data=extract(Object.values(viewer.scene.objects).filter(e=>e.model?.id===analysisId||e.id.startsWith(`${analysisId}#`)));analysisModel.destroy();return data;}
 $("#runCollisionCheck").onclick=async()=>{const a=selected(setA),b=selected(setB);if(!a||!b)return;controller=new AbortController();$("#runCollisionCheck").disabled=true;$("#cancelCollisionCheck").hidden=false;try{const started=performance.now(),objectsA=await prepare(a),objectsB=a.id===b.id?objectsA:await prepare(b);const value=Number($("#collisionRadius").value),mode=$("#clashMode").value;const output=await runXktClashAnalysis({objectsA,objectsB,mode,epsilon:mode==="intersection"?value:.001,clearance:mode==="clearance"?value:0,sameModel:a.id===b.id,signal:controller.signal,onProgress:p=>summary.textContent=p.phase==="broad"?`Broad phase... ${p.candidates} pares candidatos`:`Analisando geometrias... ${p.current} / ${p.total}`});summary.textContent="Consolidando resultados...";results=output.clashes.map((c,i)=>({id:`xkt-clash-${i+1}`,source:"xkt-geometry",setA:a.label||a.id,setB:b.label||b.id,objectA:c.objectA,objectB:c.objectB,position:c.position,intersectionPoints:c.intersectionPoints,penetrationDepth:null,status:"new"}));activeIndex=results.length?0:-1;applyFilters();summary.textContent=`Análise concluída. ${results.length} interferências encontradas.`;if(location.search.includes("debugClash"))console.info("[XKT Clash]",{grupoA:objectsA.length,grupoB:objectsB.length,paresBrutos:objectsA.length*objectsB.length,candidatos:output.candidates,clashes:results.length,tempoMs:Math.round(performance.now()-started)});}catch(error){summary.textContent=error.name==="AbortError"?"Análise cancelada.":`Não foi possível analisar a geometria XKT: ${error.message}`;if(error.name!=="AbortError")console.error("[XKT Clash]",error);}finally{$("#runCollisionCheck").disabled=false;$("#cancelCollisionCheck").hidden=true;controller=null;}};
 $("#cancelCollisionCheck").onclick=()=>controller?.abort();$("#clashMode").onchange=e=>{const clearance=e.target.value==="clearance";$("#clashDistanceLabel").firstChild.textContent=clearance?"Distância mínima (m)":"Precisão geométrica (m)";$("#collisionRadius").value=clearance?"0.050":"0.001";};$("#clashPreset").onchange=e=>{const[a,b]=e.target.value.split("|");if(a)setA.value=a;if(b)setB.value=b;};$("#clashSearch").oninput=$("#clashStatus").onchange=applyFilters;panel.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>showClash(adjacentClashIndex(activeIndex,visibleResults.length,Number(b.dataset.nav))));$("#downloadCollisionPdf").onclick=()=>{const doc=new jsPDF();doc.text("Relatório de Compatibilização BIM",14,16);results.forEach((c,i)=>doc.text(`${i+1}. ${c.objectA.modelId}/${c.objectA.objectId} x ${c.objectB.modelId}/${c.objectB.objectId}`,14,28+i*7));doc.save("compatibilizacao-bim.pdf");};$("#exportAllBcf").onclick=async()=>{for(const c of results)await exportViewpoint(c);};$("#closeCollisionPanel").onclick=()=>{controller?.abort();panel.hidden=true;restore();};render();return{destroy(){controller?.abort();restore();},getResults:()=>results,isIsolated:()=>isolated};
}
