const { chaveProjeto } = require("./_obra-ficha");
const { consolidarAtividades } = require("../atividades/atividade-agrupamento");
const { analisarDuracaoAtividade, horasAtividade, obterClassificacoesAtividade } = require("../atividades/classificacoes");
const { projetoExigeFaseItem } = require("../atividades/fase-item");

const MESES = ["JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO"];
const MESES_CURTOS = ["JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ"];
const STATUS_PENDENTES = new Set(["em progresso", "atrasado", "pausado"]);
const MARCADORES_OBRA = ["BBBB", "CCCC", "DDDD", "EEEE", "FFFF", "GGGG", "HHHH", "IIII", "JJJJ", "MMMM", "KKKK", "LLLL"];

function texto(v) { return String(v ?? "").trim(); }
function xml(v) { return texto(v).replace(/[<>&"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c])); }
function normal(v) { return texto(v).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function dataIso(v) { const s = texto(v).slice(0, 10); return /^\d{4}-\d{2}-\d{2}$/.test(s) ? s : ""; }
function formatarData(v) { const s = dataIso(v); return s ? `${s.slice(8, 10)}/${s.slice(5, 7)}/${s.slice(0, 4)}` : "Não informado"; }
function formatarHoras(v) { return `${Number(v || 0).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} h`; }
function competencia(v, longo = false) { const s = dataIso(v); if (!s) return ""; const m = Number(s.slice(5, 7)) - 1; return `${longo ? MESES[m] : MESES_CURTOS[m]}/${longo ? s.slice(0, 4) : s.slice(2, 4)}`; }
function proximaRevisao(revisoes = []) { const ultima = revisoes.map((r) => texto(r.revisao || r)).filter((r) => /^REV\d+$/.test(r)).sort((a, b) => Number(a.slice(3)) - Number(b.slice(3))).at(-1); return ultima ? `REV${String(Number(ultima.slice(3)) + 1).padStart(ultima.length - 3, "0")}` : ""; }
function validarUrl(url, obrigatoria = false) { const valor = texto(url); if (!valor && !obrigatoria) return ""; try { const parsed = new URL(valor); if (!["http:", "https:"].includes(parsed.protocol)) throw new Error(); return parsed.href; } catch (_) { throw Object.assign(new Error("Informe um link válido iniciado por http:// ou https://."), { statusCode: 422 }); } }
function mapearAtividade(r) { return { ...r, obraId: r.obra_id || r.obraId, dataInicio: r.data_inicio || r.dataInicio, horaInicio: r.hora_inicio || r.horaInicio, dataTermino: r.data_termino || r.dataTermino, horaTermino: r.hora_termino || r.horaTermino, dataPrevista: r.data_prevista || r.dataPrevista, criadoEm: r.criado_em || r.criadoEm, classificacoes: r.classificacoes || [] }; }

function unirDisciplinas({ projetosFicha = [], atividades = [], planner = [] } = {}) {
  const mapa = new Map();
  const adicionar = (nome, dados = {}) => { const chave = chaveProjeto(dados.projeto_chave || nome); if (!chave) return; const anterior = mapa.get(chave); mapa.set(chave, { projeto: anterior?.projeto || texto(nome), projetoChave: chave, codigoProjeto: anterior?.codigoProjeto || dados.codigo_projeto || dados.codigoProjeto || "", naFicha: Boolean(anterior?.naFicha || dados.naFicha), noPlanner: Boolean(anterior?.noPlanner || dados.noPlanner) }); };
  projetosFicha.forEach((p) => adicionar(p.projeto, { ...p, naFicha: true }));
  atividades.forEach((a) => adicionar(a.projeto));
  planner.forEach((p) => adicionar(p.projeto, { ...p, noPlanner: true }));
  return [...mapa.values()];
}
function obterPeriodo(atividades = []) { const datas = atividades.flatMap((a) => [dataIso(a.dataInicio || a.data_inicio), dataIso(a.dataTermino || a.data_termino)]).filter(Boolean).sort(); return { inicio: datas[0] || "", fim: datas.at(-1) || "", texto: datas.length ? `${formatarData(datas[0])} a ${formatarData(datas.at(-1))}` : "Sem período registrado", competencia: datas.length ? `${competencia(datas[0], true)} — ${competencia(datas.at(-1), true)}` : "SEM PERÍODO REGISTRADO" }; }
function atividadeNoIntervalo(a, depois, ate) { const d = dataIso(a.dataTermino || a.dataInicio || a.data_termino || a.data_inicio); return d && (!depois || d > dataIso(depois)) && (!ate || d <= dataIso(ate)); }
function mesesEntre(inicio, fim) { if (!inicio || !fim) return []; const atual = new Date(`${inicio.slice(0, 7)}-01T12:00:00Z`), limite = new Date(`${fim.slice(0, 7)}-01T12:00:00Z`), saida = []; while (atual <= limite) { saida.push(atual.toISOString().slice(0, 7)); atual.setUTCMonth(atual.getUTCMonth() + 1); } return saida; }
function blocosGantt(atividades, periodo, tamanho = 12) { const meses = mesesEntre(periodo.inicio, periodo.fim), blocos = []; for (let i = 0; i < meses.length; i += tamanho) blocos.push(meses.slice(i, i + tamanho)); return blocos; }

function analisarObra({ obra, projetosFicha = [], atividades: registros = [], planner = [], entregas = [], projetosEntrega = [], periodoInicio = "", periodoFim = "" }) {
  const historico = registros.map(mapearAtividade); const periodoHistorico = obterPeriodo(historico);
  const inicio = dataIso(periodoInicio), fim = dataIso(periodoFim);
  const atividades = historico.filter((a) => {
    const data = dataIso(a.dataTermino || a.dataInicio);
    return data && (!inicio || data >= inicio) && (!fim || data <= fim);
  });
  const periodo = obterPeriodo(atividades);
  if (inicio || fim) {
    periodo.inicio = inicio || periodoHistorico.inicio; periodo.fim = fim || periodoHistorico.fim;
    periodo.texto = periodo.inicio && periodo.fim ? `${formatarData(periodo.inicio)} a ${formatarData(periodo.fim)}` : "Sem período registrado";
    periodo.competencia = periodo.inicio && periodo.fim ? `${competencia(periodo.inicio, true)} — ${competencia(periodo.fim, true)}` : "SEM PERÍODO REGISTRADO";
  }
  const consolidadas = consolidarAtividades(atividades);
  const disciplinasBase = unirDisciplinas({ projetosFicha, atividades: historico, planner });
  const porChave = new Map(disciplinasBase.map((d) => [d.projetoChave, { ...d, registros: [] }]));
  atividades.forEach((a) => porChave.get(chaveProjeto(a.projeto))?.registros.push(a));
  const configPorChave = new Map(projetosEntrega.map((p) => [p.projeto_chave || chaveProjeto(p.projeto), p]));
  const disciplinas = [...porChave.values()].map((d) => { const cs = consolidadas.filter((a) => chaveProjeto(a.projeto) === d.projetoChave); const horas = d.registros.reduce((s, a) => s + horasAtividade(a), 0); const responsaveis = [...new Set(d.registros.map((a) => a.colaborador).filter(Boolean))]; const pendente = d.registros.some((a) => STATUS_PENDENTES.has(normal(a.status))); const cfg = configPorChave.get(d.projetoChave) || {}; return { ...d, horas, atividades: cs.length, lancamentos: d.registros.length, responsaveis, periodo: obterPeriodo(d.registros), situacao: !d.registros.length ? "Sem atividade registrada" : pendente ? "Com pendências" : "Entregue", revisao: cfg.revisao || "", tipoEmissao: cfg.tipo_emissao || "", linkProjeto: cfg.link_projeto || "" }; });
  const horasTotais = atividades.reduce((s, a) => s + horasAtividade(a), 0); const colaboradores = [...new Set(atividades.map((a) => a.colaborador).filter(Boolean))];
  const pendencias = [];
  for (const status of ["Em progresso", "Atrasado", "Pausado"]) { const afetadas = atividades.filter((a) => normal(a.status) === normal(status)); if (afetadas.length) pendencias.push({ tipo: "status", status, mensagem: `${afetadas.length} atividade(s) ainda está(ão) ${status}.`, quantidade: afetadas.length, atividadeIds: afetadas.map((a) => a.id) }); }
  disciplinas.filter((d) => d.naFicha && !d.registros.length).forEach((d) => pendencias.push({ tipo: "disciplina_sem_atividade", mensagem: `${d.projeto}: disciplina cadastrada sem atividade.`, projeto: d.projeto }));
  atividades.filter((a) => !texto(a.projeto)).forEach(() => pendencias.push({ tipo: "sem_projeto", mensagem: "Atividade sem projeto informado." }));
  const problemas = { duracao: [], classificacao: [], rateio: [] };
  atividades.forEach((a) => { const duracao = analisarDuracaoAtividade(a); if (!duracao.valido) problemas.duracao.push(a.id); const cls = obterClassificacoesAtividade(a); if (projetoExigeFaseItem(a.projeto) && !cls.length) problemas.classificacao.push(a.id); if (cls.length && duracao.valido && Math.abs(cls.reduce((s, c) => s + c.minutosDedicados, 0) - duracao.minutos) > 1) problemas.rateio.push(a.id); });
  if (problemas.duracao.length) pendencias.push({ tipo: "duracao", mensagem: `${problemas.duracao.length} atividade(s) com duração ausente ou inválida.`, quantidade: problemas.duracao.length, atividadeIds: problemas.duracao });
  if (problemas.classificacao.length) pendencias.push({ tipo: "classificacao", mensagem: `${problemas.classificacao.length} atividade(s) com classificação Fase/Item incompleta.`, quantidade: problemas.classificacao.length, atividadeIds: problemas.classificacao });
  if (problemas.rateio.length) pendencias.push({ tipo: "rateio", mensagem: `${problemas.rateio.length} atividade(s) com rateio divergente da duração.`, quantidade: problemas.rateio.length, atividadeIds: problemas.rateio });
  disciplinas.filter((d) => !d.naFicha).forEach((d) => pendencias.push({ tipo: "projeto_nao_cadastrado", mensagem: `${d.projeto}: projeto detectado ainda não cadastrado na ficha.`, projeto: d.projeto }));
  const competencias = mesesEntre(periodo.inicio, periodo.fim).map((mes) => { const lista = atividades.filter((a) => dataIso(a.dataInicio).startsWith(mes)); return { mes, label: competencia(`${mes}-01`), disciplinas: [...new Set(lista.map((a) => a.projeto).filter(Boolean))], atividades: consolidarAtividades(lista).length, horas: lista.reduce((s, a) => s + horasAtividade(a), 0) }; }).filter((c) => c.atividades);
  disciplinas.forEach((d) => { if (!d.registros.length) { const teveHistorico = historico.some((a) => chaveProjeto(a.projeto) === d.projetoChave); d.situacao = teveHistorico ? "Sem atividade no período" : "Sem atividade registrada"; } });
  return { obra, atividades, consolidadas, disciplinas, periodo, periodoEntrega: periodo, periodoHistorico, competencias, entregas, horasTotais, colaboradores, pendencias, resumo: { horasTotais, atividades: consolidadas.length, lancamentos: atividades.length, disciplinas: disciplinas.length, colaboradores: colaboradores.length, pendencias: pendencias.length } };
}

function p(texto, opts = {}) { const style = opts.style ? `<w:pStyle w:val="${xml(opts.style)}"/>` : ""; const bold = opts.bold ? "<w:b/>" : ""; return `<w:p><w:pPr>${style}<w:spacing w:after="120"/></w:pPr><w:r><w:rPr>${bold}</w:rPr><w:t xml:space="preserve">${xml(texto)}</w:t></w:r></w:p>`; }
function tabela(cabecalho, linhas, larguras = []) { const row = (cells, head) => `<w:tr>${cells.map((c, i) => `<w:tc><w:tcPr>${larguras[i] ? `<w:tcW w:w="${larguras[i]}" w:type="dxa"/>` : ""}</w:tcPr><w:p><w:r><w:rPr>${head ? "<w:b/>" : ""}</w:rPr><w:t xml:space="preserve">${xml(c)}</w:t></w:r></w:p></w:tc>`).join("")}</w:tr>`; return `<w:tbl><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:color="B7C9D6"/><w:left w:val="single" w:sz="4" w:color="B7C9D6"/><w:bottom w:val="single" w:sz="4" w:color="B7C9D6"/><w:right w:val="single" w:sz="4" w:color="B7C9D6"/><w:insideH w:val="single" w:sz="4" w:color="D9E2E8"/><w:insideV w:val="single" w:sz="4" w:color="D9E2E8"/></w:tblBorders></w:tblPr>${row(cabecalho, true)}${linhas.map((l) => row(l, false)).join("")}</w:tbl>`; }
function hyperlink(id, label) { return `<w:hyperlink r:id="${xml(id)}"><w:r><w:rPr><w:rStyle w:val="Hyperlink"/></w:rPr><w:t>${xml(label)}</w:t></w:r></w:hyperlink>`; }
function adicionarHyperlink(zip, url) { validarUrl(url, true); const arquivo = zip.file("word/_rels/document.xml.rels"); let rels = arquivo.asText(); const ids = [...rels.matchAll(/Id="rId(\d+)"/g)].map((m) => Number(m[1])); const id = `rId${Math.max(0, ...ids) + 1}`; const rel = `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${xml(url)}" TargetMode="External"/>`; rels = rels.replace("</Relationships>", `${rel}</Relationships>`); zip.file("word/_rels/document.xml.rels", rels); return id; }
function tabelaIdentificacao(d, ids) { const e = d.entrega, a = d.analise; const linhas = [["Código da obra", a.obra.codigo], ["Obra", a.obra.nome], ["Período de desenvolvimento", a.periodo.texto], ["Data da entrega", formatarData(e.data_entrega)], ["Tipo de emissão", e.tipo_emissao === "revisao" ? "Revisão" : "Entrega Inicial"], ["Revisão", e.revisao], ["Responsável pelo relatório", e.responsavel_relatorio || "Rodrigo Damasceno Nascimento"]]; const base = tabela(["Informação", "Dados"], linhas); return base + `<w:tbl><w:tr><w:tc><w:p><w:r><w:t>Documentação da entrega</w:t></w:r></w:p></w:tc><w:tc><w:p>${hyperlink(ids.processo, "Acessar documentação da entrega")}</w:p></w:tc></w:tr></w:tbl>`; }
function conclusao(analise, entrega) { return analise.pendencias.length ? p(`A presente emissão da obra ${analise.obra.codigo} — ${analise.obra.nome}, referente à ${entrega.revisao}, foi realizada com as pendências registradas no item 9.`) + p("Os arquivos correspondentes encontram-se no endereço eletrônico informado no item 2. Eventuais revisões posteriores deverão ser registradas como nova emissão, preservando-se o histórico das versões anteriores.") : p(`Com base nas atividades registradas e nos projetos relacionados neste documento, considera-se realizada a entrega da obra ${analise.obra.codigo} — ${analise.obra.nome}, referente à ${entrega.revisao}, contemplando as disciplinas relacionadas neste relatório.`) + p("Os arquivos correspondentes à presente emissão encontram-se disponibilizados no endereço eletrônico informado no item 2 deste documento.") + p("O histórico das atividades, horas registradas, responsáveis e etapas de desenvolvimento permanece consolidado no sistema interno de acompanhamento de projetos da Ribeiro Lopes Consultoria e Serviços LTDA.") + p("Eventuais revisões posteriores deverão ser registradas como nova emissão, preservando-se o histórico das versões anteriores."); }
function montarXmlRelatorio({ analise: a, entrega: e, zip }) {
  const ids = { processo: adicionarHyperlink(zip, e.link_processo) }; const config = new Map((e.projetos || []).map((x) => [x.projeto_chave, x])); a.disciplinas.forEach((d) => Object.assign(d, config.get(d.projetoChave) || {}));
  const linksDisciplinas = new Map(a.disciplinas.filter((d) => d.link_projeto || d.linkProjeto).map((d) => [d.projetoChave, adicionarHyperlink(zip, d.link_projeto || d.linkProjeto)]));
  const apresentacao = p(`O presente Relatório de Entrega tem por finalidade registrar a conclusão e a emissão dos projetos desenvolvidos para a obra ${a.obra.codigo} — ${a.obra.nome}, consolidando as disciplinas envolvidas, o histórico de desenvolvimento, as atividades executadas, os responsáveis e as informações referentes à presente emissão.`) + p("O documento também registra o endereço eletrônico disponibilizado para acesso aos arquivos da entrega, permitindo à Gerência consultar a documentação correspondente ao processo.");
  const resumo = p(`A obra ${a.obra.codigo} — ${a.obra.nome} contou com o desenvolvimento de ${a.resumo.disciplinas} disciplina(s), envolvendo ${a.resumo.colaboradores} colaborador(es) e totalizando ${formatarHoras(a.horasTotais)} registradas.`) + tabela(["Indicador", "Resultado"], [["Disciplinas", a.resumo.disciplinas], ["Atividades consolidadas", a.resumo.atividades], ["Lançamentos", a.resumo.lancamentos], ["Horas totais", formatarHoras(a.horasTotais)], ["Colaboradores", a.resumo.colaboradores], ["Período", a.periodo.texto], ["Pendências", a.resumo.pendencias]]);
  const disciplinas = tabela(["Disciplina", "Situação", "Revisão", "Atividades", "Horas", "Responsáveis"], a.disciplinas.map((d) => [d.projeto, d.situacao, d.revisao || e.revisao, d.atividades, formatarHoras(d.horas), d.responsaveis.join(", ") || "—"]));
  const historico = p(`Os registros iniciam em ${formatarData(a.periodo.inicio)} e abrangem ${a.competencias.length} competência(s) com atividades.`) + tabela(["Competência", "Disciplinas ativas", "Atividades", "Horas"], a.competencias.map((c) => [c.label, c.disciplinas.join(", "), c.atividades, formatarHoras(c.horas)]));
  const detalhes = a.disciplinas.map((d, i) => { const fases = new Map(); d.registros.forEach((r) => obterClassificacoesAtividade(r).forEach((c) => { const k = `${c.fase}|${c.item}`; fases.set(k, (fases.get(k) || 0) + c.minutosDedicados / 60); })); const trabalhos = [...new Set([...d.registros].sort((x, y) => dataIso(y.dataTermino).localeCompare(dataIso(x.dataTermino))).map((r) => texto(r.trabalhos)).filter(Boolean))]; const link = linksDisciplinas.get(d.projetoChave) ? `<w:p>${hyperlink(linksDisciplinas.get(d.projetoChave), "Acessar arquivos da disciplina")}</w:p>` : ""; return p(`6.${i + 1} ${d.projeto.toUpperCase()}`, { style: "Heading2", bold: true }) + p(`Revisão: ${d.revisao || e.revisao} | Situação: ${d.situacao} | Horas registradas: ${formatarHoras(d.horas)} | Período: ${d.periodo.texto} | Responsáveis: ${d.responsaveis.join(", ") || "Não informado"}`) + link + (fases.size ? tabela(["Fase", "Item", "Horas"], [...fases].map(([k, h]) => [...k.split("|"), formatarHoras(h)])) : p("Não há classificações Fase/Item registradas.")) + p("Principais trabalhos registrados:", { bold: true }) + trabalhos.slice(0, 10).map((t) => p(`• ${t}`)).join("") + (trabalhos.length > 10 ? p("Os demais registros constam no Anexo A.") : ""); }).join("");
  const revisoes = [...a.entregas].sort((x, y) => dataIso(x.data_entrega).localeCompare(dataIso(y.data_entrega))); const linksRevisoes = new Map(revisoes.filter((r) => r.link_processo).map((r) => [r.id, adicionarHyperlink(zip, r.link_processo)])); let histRev = tabela(["Revisão", "Data", "Tipo", "Observação", "Documentação"], revisoes.map((r) => [r.revisao, formatarData(r.data_entrega), r.tipo_emissao === "revisao" ? "Revisão" : "Entrega inicial", r.observacoes || "—", r.link_processo ? "Link disponível abaixo" : "—"])) + revisoes.filter((r) => linksRevisoes.has(r.id)).map((r) => `<w:p><w:r><w:t>${xml(`${r.revisao}: `)}</w:t></w:r>${hyperlink(linksRevisoes.get(r.id), "Acessar documentação")}</w:p>`).join(""); const anterior = revisoes.filter((r) => r.id !== e.id && dataIso(r.data_entrega) < dataIso(e.data_entrega)).at(-1); if (e.tipo_emissao === "revisao" && anterior) { const mudancas = a.disciplinas.map((d) => { const rs = d.registros.filter((r) => atividadeNoIntervalo(r, anterior.data_entrega, e.data_entrega)); return [d.projeto, consolidarAtividades(rs).length, formatarHoras(rs.reduce((s, r) => s + horasAtividade(r), 0)), [...new Set(rs.flatMap((r) => obterClassificacoesAtividade(r).map((c) => `${c.fase} / ${c.item}`)))].join(", ") || "—"]; }).filter((r) => r[1]); histRev += p(`ALTERAÇÕES DESDE A ${anterior.revisao}`, { style: "Heading2", bold: true }) + tabela(["Disciplina", "Atividades após revisão anterior", "Horas", "Fases / itens movimentados"], mudancas); }
  const equipe = a.colaboradores.map((nome) => { const rs = a.atividades.filter((r) => r.colaborador === nome), hs = rs.reduce((s, r) => s + horasAtividade(r), 0); return [nome, consolidarAtividades(rs).length, rs.length, formatarHoras(hs), a.horasTotais ? `${(hs / a.horasTotais * 100).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%` : "0%"]; });
  const pend = a.pendencias.length ? a.pendencias.map((x) => p(`⚠ ${x.mensagem}`)).join("") : p("Na data de emissão deste relatório, não foram identificadas pendências internas registradas no sistema que impeçam a entrega das disciplinas relacionadas neste documento."); const observacoes = texto(e.observacoes) ? p("Observações da entrega:", { bold: true }) + p(e.observacoes) : "";
  const anexo = tabela(["Disciplina", "Fase / Item", "Ativ.", "Horas", "Período", "Status", "Colaboradores"], a.disciplinas.flatMap((d) => { const grupos = new Map(); d.registros.forEach((r) => { const cs = obterClassificacoesAtividade(r); (cs.length ? cs : [{ fase: r.fase || "Sem fase", item: r.item || "Sem item", minutosDedicados: horasAtividade(r) * 60 }]).forEach((c) => { const k = `${c.fase} / ${c.item}`; const g = grupos.get(k) || { registros: [], horas: 0 }; g.registros.push(r); g.horas += c.minutosDedicados / 60; grupos.set(k, g); }); }); return [...grupos].map(([fi, g]) => [d.projeto, fi, consolidarAtividades(g.registros).length, formatarHoras(g.horas), obterPeriodo(g.registros).texto, [...new Set(g.registros.map((r) => r.status))].join(", "), [...new Set(g.registros.map((r) => r.colaborador))].join(", ")]); }));
  const gantt = blocosGantt(a.atividades, a.periodo).map((bloco, i) => p(`B.${i + 1} — ${competencia(`${bloco[0]}-01`)} A ${competencia(`${bloco.at(-1)}-01`)}`, { style: "Heading2", bold: true }) + tabela(["PROCESSO", "HORAS", ...bloco.map((m) => competencia(`${m}-01`))], a.disciplinas.map((d) => [d.projeto, formatarHoras(d.horas), ...bloco.map((m) => d.registros.some((r) => dataIso(r.dataInicio).startsWith(m)) ? "■" : "")] ))).join("");
  return { AAAA: `${a.obra.codigo} — ${a.obra.nome}`, ENTREGA: e.tipo_emissao === "revisao" ? "REVISÃO" : "ENTREGA INICIAL", REVISAO: e.revisao, DATA_ENTREGA: formatarData(e.data_entrega), PERIODO_RELATORIO: a.periodo.competencia, BBBB: apresentacao, CCCC: tabelaIdentificacao({ analise: a, entrega: e }, ids), DDDD: resumo, EEEE: disciplinas, FFFF: historico, GGGG: detalhes, HHHH: histRev, IIII: p(`Foram identificados ${a.colaboradores.length} colaborador(es), com ${formatarHoras(a.horasTotais)} registradas.`) + tabela(["Colaborador", "Atividades", "Lançamentos", "Horas", "Participação"], equipe), JJJJ: pend + observacoes, MMMM: conclusao(a, e), KKKK: anexo, LLLL: p("GANTT MACRO DA EXECUÇÃO REAL", { bold: true }) + gantt };
}
function prepararTemplate(zip) { const arquivo = zip.file("word/document.xml"); let doc = arquivo.asText(); const textoVisivel = (trecho) => [...trecho.matchAll(/<w:t\b[^>]*>([\s\S]*?)<\/w:t>/g)].map((m) => m[1]).join("").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">"); doc = doc.replace(/<w:p\b[^>]*>[\s\S]*?<\/w:p>/g, (paragrafo) => { const visivel = textoVisivel(paragrafo); if (visivel.includes("[DATA_ENTREGA[")) return "<w:p><w:r><w:t>[DATA_ENTREGA]</w:t></w:r></w:p>"; const marcador = MARCADORES_OBRA.find((item) => visivel.includes(`[${item}]`)); return marcador ? `<w:p><w:r><w:t>[@${marcador}]</w:t></w:r></w:p>` : paragrafo; }); zip.file("word/document.xml", doc); }
function validarDocumento(zip) { const doc = zip.file("word/document.xml").asText(); const restantes = ["AAAA", "ENTREGA", "REVISAO", "DATA_ENTREGA", "PERIODO_RELATORIO", ...MARCADORES_OBRA].filter((m) => doc.includes(`[${m}]`) || doc.includes(`[@${m}]`)); if (restantes.length) throw Object.assign(new Error(`Marcadores não substituídos no documento: ${restantes.join(", ")}.`), { statusCode: 500 }); if (doc.includes("&lt;w:tbl")) throw Object.assign(new Error("Uma tabela OpenXML foi inserida como texto escapado."), { statusCode: 500 }); if ((doc.match(/<w:tbl>/g) || []).length < 2) throw Object.assign(new Error("Os anexos não contêm tabelas OpenXML reais."), { statusCode: 500 }); return true; }
function nomeArquivo(obra, revisao) { const slug = `${obra.codigo}-${obra.nome}-${revisao}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^A-Za-z0-9-]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, ""); return `relatorio-entrega-${slug}.docx`; }

async function carregarDadosObra(obraId, request, localizarObra, entregaId = "") {
  const obra = await localizarObra(obraId); if (!obra) throw Object.assign(new Error("Obra não encontrada."), { statusCode: 404 });
  const filtro = encodeURIComponent(obra.id);
  const [projetosFicha, atividadesDb, planner, entregas] = await Promise.all([
    request("obra_projetos", `?obra_id=eq.${filtro}&select=*&order=projeto.asc`),
    request("atividades_colaboradores", `?obra_id=eq.${filtro}&select=*&order=data_inicio.asc`),
    request("planner_checklists", `?obra_id=eq.${filtro}&select=*&order=data_inicio.asc`),
    request("obra_entregas", `?obra_id=eq.${filtro}&select=*&order=data_entrega.asc,criado_em.asc`)
  ]);
  const ids = (atividadesDb || []).map((a) => a.id).filter(Boolean); const classificacoes = [];
  for (let i = 0; i < ids.length; i += 75) classificacoes.push(...await request("atividade_classificacoes", `?atividade_id=in.(${ids.slice(i, i + 75).map(encodeURIComponent).join(",")})&select=*`));
  const porAtividade = new Map(); classificacoes.forEach((c) => { const lista = porAtividade.get(c.atividade_id) || []; lista.push(c); porAtividade.set(c.atividade_id, lista); });
  const atividades = (atividadesDb || []).map((a) => ({ ...a, classificacoes: porAtividade.get(a.id) || [] }));
  const entrega = entregaId ? (entregas || []).find((x) => String(x.id) === String(entregaId)) : null;
  if (entregaId && !entrega) throw Object.assign(new Error("Entrega não encontrada para a obra informada."), { statusCode: 404 });
  const projetosEntrega = entrega ? await request("obra_entrega_projetos", `?entrega_id=eq.${encodeURIComponent(entrega.id)}&select=*&order=projeto.asc`) : [];
  return { obra, projetosFicha: projetosFicha || [], atividades, planner: planner || [], entregas: entregas || [], projetosEntrega, entrega };
}

module.exports = { MARCADORES_OBRA, adicionarHyperlink, analisarObra, atividadeNoIntervalo, blocosGantt, carregarDadosObra, formatarData, mapearAtividade, montarXmlRelatorio, nomeArquivo, obterPeriodo, prepararTemplate, proximaRevisao, unirDisciplinas, validarDocumento, validarUrl };