const { chaveProjeto } = require("./_obra-ficha");
const { consolidarAtividades, obterChaveAtividadeConsolidada } = require("../atividades/atividade-agrupamento");
const { criarCelulaTabelaXml, criarTabelaXml, criarEspacoAposTabelaXml, criarParagrafoXml } = require("./_docx-tabelas");
const { gerarGanttTabelaXml } = require("./_relatorio-gantt");
const { analisarDuracaoAtividade, horasAtividade, obterClassificacoesAtividade } = require("../atividades/classificacoes");
const { projetoExigeFaseItem } = require("../atividades/fase-item");

const MESES = ["JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO"];
const MESES_CURTOS = ["JAN", "FEV", "MAR", "ABR", "MAI", "JUN", "JUL", "AGO", "SET", "OUT", "NOV", "DEZ"];
const STATUS_PENDENTES = new Set(["em progresso", "atrasado", "pausado"]);
const MARCADORES_OBRA = ["BBBB", "CCCC", "DDDD", "EEEE", "FFFF", "GGGG", "HHHH", "IIII", "JJJJ", "MMMM", "KKKK", "LLLL"];
const CORES_RELATORIO = Object.freeze({ cabecalho: "1F4E78", fundoClaro: "EAF2F8", borda: "B4C6E7", textoCabecalho: "FFFFFF" });

function texto(v) { return String(v ?? "").trim(); }
function xml(v) { return texto(v).replace(/[<>&"]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;" }[c])); }
function normal(v) { return texto(v).normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); }
function dataIso(v) { const s = texto(v).slice(0, 10); return /^\d{4}-\d{2}-\d{2}$/.test(s) ? s : ""; }
function formatarData(v) { const s = dataIso(v); return s ? `${s.slice(8, 10)}/${s.slice(5, 7)}/${s.slice(0, 4)}` : "Não informado"; }
function formatarHoras(v) { return `${Number(v || 0).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} h`; }
function competencia(v, longo = false) { const s = dataIso(v); if (!s) return ""; const m = Number(s.slice(5, 7)) - 1; return `${longo ? MESES[m] : MESES_CURTOS[m]}/${longo ? s.slice(0, 4) : s.slice(2, 4)}`; }
function proximaRevisao(revisoes = []) { const ultima = revisoes.map((r) => texto(r.revisao || r)).filter((r) => /^REV\d+$/.test(r)).sort((a, b) => Number(a.slice(3)) - Number(b.slice(3))).at(-1); return ultima ? `REV${String(Number(ultima.slice(3)) + 1).padStart(ultima.length - 3, "0")}` : ""; }
function validarUrl(url, obrigatoria = false) { const valor = texto(url); if (!valor && !obrigatoria) return ""; try { const parsed = new URL(valor); if (!["http:", "https:"].includes(parsed.protocol)) throw new Error(); return parsed.href; } catch (_) { throw Object.assign(new Error("Informe um link válido iniciado por http:// ou https://."), { statusCode: 422 }); } }
function mapearAtividade(r) { return { ...r, obraId: r.obra_id || r.obraId, dataInicio: r.data_inicio || r.dataInicio, horaInicio: r.hora_inicio || r.horaInicio, dataTermino: r.data_termino || r.dataTermino, horaTermino: r.hora_termino || r.horaTermino, dataPrevista: r.data_prevista || r.dataPrevista, criadoEm: r.criado_em || r.criadoEm, classificacoes: r.classificacoes || [] }; }

function unirDisciplinas({ projetosFicha = [], atividades = [], planner = [] } = {}) {
  const mapa = new Map();
  const adicionar = (nome, dados = {}) => { const chave = chaveProjeto(dados.projeto_chave || nome); if (!chave) return; const anterior = mapa.get(chave); mapa.set(chave, { projeto: anterior?.projeto || texto(nome), projetoChave: chave, codigoProjeto: anterior?.codigoProjeto || dados.codigo_projeto || dados.codigoProjeto || "", naFicha: Boolean(anterior?.naFicha || dados.naFicha), noPlanner: Boolean(anterior?.noPlanner || dados.noPlanner) }); };
  projetosFicha.forEach((p) => adicionar(p.projeto, { ...p, naFicha: true }));
  atividades.forEach((a) => adicionar(a.projeto));
  planner.forEach((p) => adicionar(p.projeto, { ...p, noPlanner: true }));
  return [...mapa.values()];
}
function obterPeriodo(atividades = []) { const datas = atividades.flatMap((a) => [dataIso(a.dataInicio || a.data_inicio), dataIso(a.dataTermino || a.data_termino)]).filter(Boolean).sort(); return { inicio: datas[0] || "", fim: datas.at(-1) || "", texto: datas.length ? `${formatarData(datas[0])} a ${formatarData(datas.at(-1))}` : "Sem período registrado", competencia: datas.length ? `${competencia(datas[0], true)} — ${competencia(datas.at(-1), true)}` : "SEM PERÍODO REGISTRADO" }; }
function atividadeNoIntervalo(a, depois, ate) { const d = dataIso(a.dataTermino || a.dataInicio || a.data_termino || a.data_inicio); return d && (!depois || d > dataIso(depois)) && (!ate || d <= dataIso(ate)); }
function mesesEntre(inicio, fim) { if (!inicio || !fim) return []; const atual = new Date(`${inicio.slice(0, 7)}-01T12:00:00Z`), limite = new Date(`${fim.slice(0, 7)}-01T12:00:00Z`), saida = []; while (atual <= limite) { saida.push(atual.toISOString().slice(0, 7)); atual.setUTCMonth(atual.getUTCMonth() + 1); } return saida; }
function blocosGantt(atividades, periodo, tamanho = 12) { const meses = mesesEntre(periodo.inicio, periodo.fim), blocos = []; for (let i = 0; i < meses.length; i += tamanho) blocos.push(meses.slice(i, i + tamanho)); return blocos; }

function analisarObra({ obra, projetosFicha = [], atividades: registros = [], planner = [], entregas = [], projetosEntrega = [], periodoInicio = "", periodoFim = "" }) {
  const historico = registros.map((registro) => ({ ...mapearAtividade(registro), obraId: registro.obra_id || registro.obraId || obra.id, obraCodigo: registro.obra_codigo || registro.obraCodigo || obra.codigo, obra: registro.obra || obra.nome })); const periodoHistorico = obterPeriodo(historico);
  const inicio = dataIso(periodoInicio), fim = dataIso(periodoFim);
  const atividades = historico.filter((a) => {
    const data = dataIso(a.dataTermino || a.dataInicio);
    return data && (!inicio || data >= inicio) && (!fim || data <= fim);
  });
  const periodo = obterPeriodo(atividades);
  if (inicio || fim) {
    periodo.inicio = inicio || periodoHistorico.inicio; periodo.fim = fim || periodoHistorico.fim;
    periodo.texto = periodo.inicio && periodo.fim ? `${formatarData(periodo.inicio)} a ${formatarData(periodo.fim)}` : "Sem período registrado";
    periodo.competencia = periodo.inicio && periodo.fim ? `${competencia(periodo.inicio, true)} — ${competencia(periodo.fim, true)}` : "SEM PERÍODO REGISTRADO";
  }
  const consolidadas = consolidarAtividades(atividades);
  const disciplinasBase = unirDisciplinas({ projetosFicha, atividades: historico, planner });
  const porChave = new Map(disciplinasBase.map((d) => [d.projetoChave, { ...d, registros: [] }]));
  atividades.forEach((a) => porChave.get(chaveProjeto(a.projeto))?.registros.push(a));
  const configPorChave = new Map(projetosEntrega.map((p) => [p.projeto_chave || chaveProjeto(p.projeto), p]));
  const disciplinas = [...porChave.values()].map((d) => { const cs = consolidadas.filter((a) => chaveProjeto(a.projeto) === d.projetoChave); const horas = d.registros.reduce((s, a) => s + horasAtividade(a), 0); const responsaveis = [...new Set(d.registros.map((a) => a.colaborador).filter(Boolean))]; const pendente = d.registros.some((a) => STATUS_PENDENTES.has(normal(a.status))); const cfg = configPorChave.get(d.projetoChave) || {}; return { ...d, horas, atividades: cs.length, lancamentos: d.registros.length, responsaveis, periodo: obterPeriodo(d.registros), situacao: !d.registros.length ? "Sem atividade registrada" : pendente ? "Com pendências" : "Entregue", revisao: cfg.revisao || "", tipoEmissao: cfg.tipo_emissao || "", linkProjeto: cfg.link_projeto || "" }; });
  // Única fonte formal do Word: já consolidada pela chave oficial e sem disciplinas vazias.
  const disciplinasRelatorio = disciplinas.filter((d) => Number(d.horas || 0) > 0)
    .sort((a, b) => b.horas - a.horas || a.projeto.localeCompare(b.projeto, "pt-BR"));
  const horasTotais = atividades.reduce((s, a) => s + horasAtividade(a), 0); const colaboradores = [...new Set(atividades.map((a) => a.colaborador).filter(Boolean))];
  const pendencias = [];
  for (const status of ["Em progresso", "Atrasado", "Pausado"]) { const afetadas = atividades.filter((a) => normal(a.status) === normal(status)); if (afetadas.length) pendencias.push({ tipo: "status", status, mensagem: `${afetadas.length} atividade(s) ainda está(ão) ${status}.`, quantidade: afetadas.length, atividadeIds: afetadas.map((a) => a.id) }); }
  atividades.filter((a) => !texto(a.projeto)).forEach(() => pendencias.push({ tipo: "sem_projeto", mensagem: "Atividade sem projeto informado." }));
  const problemas = { duracao: [], classificacao: [], rateio: [] };
  atividades.forEach((a) => { const duracao = analisarDuracaoAtividade(a); if (!duracao.valido) problemas.duracao.push(a.id); const cls = obterClassificacoesAtividade(a); if (projetoExigeFaseItem(a.projeto) && !cls.length) problemas.classificacao.push(a.id); if (cls.length && duracao.valido && Math.abs(cls.reduce((s, c) => s + c.minutosDedicados, 0) - duracao.minutos) > 1) problemas.rateio.push(a.id); });
  if (problemas.duracao.length) pendencias.push({ tipo: "duracao", mensagem: `${problemas.duracao.length} atividade(s) com duração ausente ou inválida.`, quantidade: problemas.duracao.length, atividadeIds: problemas.duracao });
  if (problemas.classificacao.length) pendencias.push({ tipo: "classificacao", mensagem: `${problemas.classificacao.length} atividade(s) com classificação Fase/Item incompleta.`, quantidade: problemas.classificacao.length, atividadeIds: problemas.classificacao });
  if (problemas.rateio.length) pendencias.push({ tipo: "rateio", mensagem: `${problemas.rateio.length} atividade(s) com rateio divergente da duração.`, quantidade: problemas.rateio.length, atividadeIds: problemas.rateio });
  disciplinas.filter((d) => !d.naFicha).forEach((d) => pendencias.push({ tipo: "projeto_nao_cadastrado", mensagem: `${d.projeto}: projeto detectado ainda não cadastrado na ficha.`, projeto: d.projeto }));
  const competencias = mesesEntre(periodo.inicio, periodo.fim).map((mes) => { const lista = atividades.filter((a) => dataIso(a.dataInicio).startsWith(mes) && horasAtividade(a) > 0); const ativas = new Map(); lista.forEach((a) => { const chave = chaveProjeto(a.projeto); if (chave && disciplinasRelatorio.some((d) => d.projetoChave === chave)) ativas.set(chave, disciplinasRelatorio.find((d) => d.projetoChave === chave).projeto); }); return { mes, label: competencia(`${mes}-01`), disciplinas: [...ativas.values()], atividades: consolidarAtividades(lista).length, horas: lista.reduce((s, a) => s + horasAtividade(a), 0) }; }).filter((c) => c.horas > 0);
  disciplinas.forEach((d) => { if (!d.registros.length) { const teveHistorico = historico.some((a) => chaveProjeto(a.projeto) === d.projetoChave); d.situacao = teveHistorico ? "Sem atividade no período" : "Sem atividade registrada"; } });
  return { obra, atividades, consolidadas, disciplinas, disciplinasRelatorio, periodo, periodoEntrega: periodo, periodoHistorico, competencias, entregas, horasTotais, colaboradores, pendencias, resumo: { horasTotais, atividades: consolidadas.length, lancamentos: atividades.length, disciplinas: disciplinasRelatorio.length, colaboradores: colaboradores.length, pendencias: pendencias.length } };
}

function p(conteudo, opts = {}) { return criarParagrafoXml(conteudo, opts); }
function tabela(cabecalho, linhas, colunas = []) {
  return criarTabelaXml(cabecalho, linhas, { colunas, larguraTotal: colunas.reduce((s, c) => s + Number((typeof c === "object" ? c.largura : c) || 0), 0), tamanhoFonte: 9, tamanhoFonteCabecalho: 9 });
}
function tabelaChaveValor(linhas) { const colunas = [{ largura: 2600, fill: CORES_RELATORIO.cabecalho, color: "FFFFFF", bold: true, margemVertical: 120, margemHorizontal: 140 }, { largura: 5855, fill: CORES_RELATORIO.fundoClaro, color: "000000", margemVertical: 120, margemHorizontal: 140 }]; return criarTabelaXml([], linhas, { colunas, larguraTotal: 8455, tamanhoFonte: 10 }); }
function listaTrabalhos(trabalhos) { return trabalhos.map((item) => p(`• ${item}`, { alignment: "left", after: 40 })).join(""); }
function hyperlink(id, label) { return `<w:hyperlink r:id="${xml(id)}"><w:r><w:rPr><w:rStyle w:val="Hyperlink"/><w:sz w:val="20"/></w:rPr><w:t>${xml(label)}</w:t></w:r></w:hyperlink>`; }
function adicionarHyperlink(zip, url) { validarUrl(url, true); const arquivo = zip.file("word/_rels/document.xml.rels"); let rels = arquivo.asText(); const ids = [...rels.matchAll(/Id="rId(\d+)"/g)].map((m) => Number(m[1])); const id = `rId${Math.max(0, ...ids) + 1}`; const rel = `<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${xml(url)}" TargetMode="External"/>`; rels = rels.replace("</Relationships>", `${rel}</Relationships>`); zip.file("word/_rels/document.xml.rels", rels); return id; }
function tabelaIdentificacao(d, ids) { const e = d.entrega, a = d.analise; const linhas = [["Código da obra", a.obra.codigo], ["Obra", a.obra.nome], ["Período de desenvolvimento", a.periodo.texto], ["Data da entrega", formatarData(e.data_entrega)], ["Tipo de emissão", e.tipo_emissao === "revisao" ? "Revisão" : "Entrega Inicial"], ["Revisão", e.revisao], ["Responsável pelo relatório", e.responsavel_relatorio || "Rodrigo Damasceno Nascimento"]]; return tabelaChaveValor(linhas) + criarEspacoAposTabelaXml(8) + p("Documentação da entrega:", { bold: true, alignment: "left", firstLine: 0, keepNext: true }) + p(hyperlink(ids.processo, e.link_processo), { xmlBruto: true, alignment: "left", firstLine: 0, tamanhoFonte: 10 }); }
function conclusao(analise, entrega) { return analise.pendencias.length ? p(`A presente emissão da obra ${analise.obra.codigo} — ${analise.obra.nome}, referente à ${entrega.revisao}, foi realizada com as pendências registradas no item 9.`) + p("Os arquivos correspondentes encontram-se no endereço eletrônico informado no item 2. Eventuais revisões posteriores deverão ser registradas como nova emissão, preservando-se o histórico das versões anteriores.") : p(`Com base nas atividades registradas e nos projetos relacionados neste documento, considera-se realizada a entrega da obra ${analise.obra.codigo} — ${analise.obra.nome}, referente à ${entrega.revisao}, contemplando as disciplinas relacionadas neste relatório.`) + p("Os arquivos correspondentes à presente emissão encontram-se disponibilizados no endereço eletrônico informado no item 2 deste documento.") + p("O histórico das atividades, horas registradas, responsáveis e etapas de desenvolvimento permanece consolidado no sistema interno de acompanhamento de projetos da Ribeiro Lopes Consultoria e Serviços LTDA.") + p("Eventuais revisões posteriores deverão ser registradas como nova emissão, preservando-se o histórico das versões anteriores."); }
const LARGURA_TABELAS_ANEXO = 13750;
function chaveOrdenacaoRegistro(r = {}) { return [r.dataInicio, r.horaInicio, r.dataTermino, r.horaTermino, r.criadoEm].map((v) => texto(v)).join("|"); }
function agruparLancamentosParaAnexo(registros = [], consolidadas = []) {
  const mapaConsolidadas = new Map(consolidadas.map((a) => [a.chaveConsolidada || obterChaveAtividadeConsolidada(a), a]));
  const grupos = new Map();
  registros.filter((r) => horasAtividade(r) > 0).forEach((r) => { const chave = obterChaveAtividadeConsolidada(r); if (!grupos.has(chave)) grupos.set(chave, []); grupos.get(chave).push(r); });
  return [...grupos].map(([chave, lista]) => ({ atividade: mapaConsolidadas.get(chave) || consolidarAtividades(lista)[0], registros: [...lista].sort((a, b) => chaveOrdenacaoRegistro(a).localeCompare(chaveOrdenacaoRegistro(b), "pt-BR")) }))
    .sort((a, b) => [a.atividade.obraCodigo, a.atividade.obra, a.atividade.projeto, a.atividade.etapa].map(texto).join("|").localeCompare([b.atividade.obraCodigo, b.atividade.obra, b.atividade.projeto, b.atividade.etapa].map(texto).join("|"), "pt-BR", { sensitivity: "base", numeric: true }));
}
function criarCabecalhoGrupoAnexo(grupo) {
  const a = grupo.atividade; const linhas = [["OBRA", `${a.obraCodigo ? `${a.obraCodigo} — ` : ""}${a.obra || "Não informada"}`], ["DISCIPLINA / ETAPA", `${a.projeto || "Não informada"} — ${a.etapa || "Não informada"}`], ["SITUAÇÃO", `${a.status || "Não informado"} · ${a.prioridade || "Não informada"}`], ["RESUMO", `${grupo.registros.length} lançamento(s) · ${formatarHoras(grupo.registros.reduce((total, r) => total + horasAtividade(r), 0))}`]];
  const colunas = [{ largura: 1800, fill: "1F4E78", color: "FFFFFF", bold: true, keepNext: true, margemVertical: 120, margemHorizontal: 140 }, { largura: 11950, fill: "EAF2F8", color: "000000", keepNext: true, margemVertical: 120, margemHorizontal: 140 }];
  return `<w:tbl><w:tblPr><w:tblW w:w="13750" w:type="dxa"/><w:jc w:val="center"/><w:tblInd w:w="0" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblCellSpacing w:w="0" w:type="dxa"/></w:tblPr><w:tblGrid><w:gridCol w:w="1800"/><w:gridCol w:w="11950"/></w:tblGrid>${linhas.map((linha) => `<w:tr><w:trPr><w:cantSplit/></w:trPr>${linha.map((c, i) => criarCelulaTabelaXml(c, false, { ...colunas[i], tamanhoFonte: 8 }, 8)).join("")}</w:tr>`).join("")}</w:tbl>`;
}
function gerarAnexoDetalhado(registros, consolidadas) {
  const grupos = agruparLancamentosParaAnexo(registros, consolidadas);
  if (!grupos.length) return criarTabelaXml(["Atividades"], [["Sem registros"]], { colunas: [{ largura: LARGURA_TABELAS_ANEXO }], larguraTotal: LARGURA_TABELAS_ANEXO });
  const colunas = [{ largura: 1100, alinhamento: "center", noWrap: true }, { largura: 1300 }, { largura: 1100, alinhamento: "center", noWrap: true }, { largura: 850, alinhamento: "center", noWrap: true }, { largura: 4800 }, { largura: 4600 }];
  return grupos.map((g) => criarCabecalhoGrupoAnexo(g) + criarTabelaXml(["Data", "Colaborador", "Horário", "Duração", "Trabalho executado", "Observações"], g.registros.map((r) => [formatarData(r.dataInicio), r.colaborador || "Não informado", `${texto(r.horaInicio).slice(0, 5) || "—"}–${texto(r.horaTermino).slice(0, 5) || "—"}`, formatarHoras(horasAtividade(r)), r.trabalhos || "Trabalho não informado", r.observacoes || r.observacao || "—"]), { colunas, larguraTotal: LARGURA_TABELAS_ANEXO, tamanhoFonte: 8, tamanhoFonteCabecalho: 8 }) + criarEspacoAposTabelaXml(10)).join("");
}
function diasLancamento(r, periodo) { const inicio = dataIso(r.dataInicio), fim = dataIso(r.dataTermino || r.dataInicio); if (!inicio || !fim || horasAtividade(r) <= 0) return []; const a = inicio < periodo.inicio ? periodo.inicio : inicio, b = fim > periodo.fim ? periodo.fim : fim, dias = []; if (!a || !b || a > b) return dias; for (let d = new Date(`${a}T12:00:00Z`), limite = new Date(`${b}T12:00:00Z`); d <= limite; d.setUTCDate(d.getUTCDate() + 1)) dias.push(d.toISOString().slice(0, 10)); return dias; }
function montarGantt(a, ds) {
  const dias = (registros) => [...new Set(registros.flatMap((r) => diasLancamento(r, a.periodo)))].sort();
  const projetos = ds.map((d) => { const fases = new Map(); d.registros.forEach((r) => { const cs = obterClassificacoesAtividade(r); if (cs.length) cs.forEach((c) => { const key = `${c.fase || "Fase não informada"} — ${c.item || "Item não informado"}`; const atual = fases.get(key) || { nivel: "fase", nome: key, horas: 0, registros: [] }; atual.horas += Number(c.minutosDedicados || 0) / 60; atual.registros.push(r); fases.set(key, atual); }); else { const key = r.etapa || "Etapa não informada"; const atual = fases.get(key) || { nivel: "fase", nome: key, horas: 0, registros: [] }; atual.horas += horasAtividade(r); atual.registros.push(r); fases.set(key, atual); } }); return { linha: { nivel: "projeto", nome: d.projeto, horas: d.horas, dias: dias(d.registros) }, fases: [...fases.values()].map((f) => ({ nivel: f.nivel, nome: f.nome, horas: f.horas, dias: dias(f.registros) })) }; });
  const intervalo = a.periodo.inicio && a.periodo.fim ? (new Date(`${a.periodo.fim}T12:00:00Z`) - new Date(`${a.periodo.inicio}T12:00:00Z`)) / 864e5 + 1 : 0;
  return { periodo: { inicio: a.periodo.inicio, fim: a.periodo.fim }, horasTotaisRelatorio: a.horasTotais, modoRelatorio: intervalo > 31 ? "mensal" : "semanal", obras: [{ codigo: a.obra.codigo, nome: a.obra.nome, horas: a.horasTotais, dias: dias(a.atividades), linha: { nivel: "obra", nome: `${a.obra.codigo} — ${a.obra.nome}`, horas: a.horasTotais, dias: dias(a.atividades) }, projetos }] };
}
function normalizarCelulasGantt(xmlGantt) { return xmlGantt.replace(/<w:tc>([\s\S]*?)<\/w:tc>/g, (tc) => tc.replace(/<w:pPr>([\s\S]*?)<\/w:pPr>/g, (pPr, conteudo) => `<w:pPr>${/<w:ind\b/.test(conteudo) ? conteudo.replace(/<w:ind\b[^>]*\/>/, '<w:ind w:left="0" w:right="0" w:firstLine="0"/>') : `${conteudo}<w:ind w:left="0" w:right="0" w:firstLine="0"/>`}</w:pPr>`)); }
function montarXmlRelatorio({ analise: a, entrega: e, zip }) {
  const ds = a.disciplinasRelatorio || a.disciplinas.filter((d) => Number(d.horas || 0) > 0);
  const config = new Map((e.projetos || []).map((x) => [chaveProjeto(x.projeto_chave || x.projeto), x])); ds.forEach((d) => Object.assign(d, config.get(d.projetoChave) || {}));
  const ids = { processo: adicionarHyperlink(zip, e.link_processo) };
  const links = new Map(ds.filter((d) => d.link_projeto || d.linkProjeto).map((d) => [d.projetoChave, adicionarHyperlink(zip, d.link_projeto || d.linkProjeto)]));
  const apresentacao = p(`O presente Relatório de Entrega registra a conclusão e a emissão dos projetos desenvolvidos para a obra ${a.obra.codigo} — ${a.obra.nome}, consolidando as disciplinas efetivamente trabalhadas, o histórico, as atividades, os responsáveis e os dados desta emissão.`, { firstLine: 567 }) + p("O endereço eletrônico completo da documentação é apresentado para consulta digital e também para identificação na versão impressa.", { firstLine: 567 });
  const resumo = p(`A obra ${a.obra.codigo} — ${a.obra.nome} contou com o desenvolvimento de ${ds.length} disciplina(s), envolvendo ${a.resumo.colaboradores} colaborador(es) e totalizando ${formatarHoras(a.horasTotais)} registradas.`, { firstLine: 567 }) + tabela(["Indicador", "Resultado", "Indicador", "Resultado"], [["Disciplinas", ds.length, "Colaboradores", a.resumo.colaboradores], ["Atividades", a.resumo.atividades, "Lançamentos", a.resumo.lancamentos], ["Horas", formatarHoras(a.horasTotais), "Período", `${a.competencias.length} competência(s)`], ["Revisão", e.revisao, "Pendências", a.pendencias.length]], [{ largura: 2000, bold: true }, { largura: 1100, alinhamento: "center", noWrap: true }, { largura: 2100, bold: true }, { largura: 3255, alinhamento: "center" }]);
  const disciplinas = tabela(["Disciplina", "Revisão", "Ativ.", "Horas", "Responsáveis"], ds.map((d) => [d.projeto, d.revisao || e.revisao, d.atividades, formatarHoras(d.horas), d.responsaveis.join(", ") || "—"]), [{ largura: 2500 }, { largura: 900, alinhamento: "center", noWrap: true }, { largura: 900, alinhamento: "center", noWrap: true }, { largura: 1100, alinhamento: "center", noWrap: true }, { largura: 3055 }]);
  const historico = p(`Os registros iniciam em ${formatarData(a.periodo.inicio)} e abrangem ${a.competencias.length} competência(s) com esforço registrado.`, { firstLine: 567 }) + tabela(["Competência", "Disciplinas ativas", "Atividades", "Horas"], a.competencias.map((c) => [c.label, c.disciplinas.join(", "), c.atividades, formatarHoras(c.horas)]), [{ largura: 1300, alinhamento: "center", noWrap: true }, { largura: 4055 }, { largura: 1200, alinhamento: "center", noWrap: true }, { largura: 1900, alinhamento: "center", noWrap: true }]);
  const detalhes = ds.map((d, i) => { const fases = new Map(); d.registros.forEach((r) => obterClassificacoesAtividade(r).forEach((c) => { const h = Number(c.minutosDedicados || 0) / 60; if (h > 0) { const k = `${c.fase}|${c.item}`; fases.set(k, (fases.get(k) || 0) + h); } })); const trabalhos = [...new Set([...d.registros].sort((x, y) => dataIso(y.dataTermino).localeCompare(dataIso(x.dataTermino))).map((r) => texto(r.trabalhos)).filter(Boolean))].slice(0, 10); const link = links.get(d.projetoChave) ? `<w:p><w:pPr><w:spacing w:after="100"/></w:pPr>${hyperlink(links.get(d.projetoChave), d.link_projeto || d.linkProjeto)}</w:p>` : ""; return p(`6.${i + 1} ${d.projeto.toUpperCase()}`, { bold: true, keepNext: true, keepLines: true, alignment: "left", firstLine: 0 }) + tabelaChaveValor([["Revisão", d.revisao || e.revisao], ["Horas registradas", formatarHoras(d.horas)], ["Período", d.periodo.texto], ["Responsáveis", d.responsaveis.join(", ") || "—"]]) + link + (fases.size ? p("FASES E ITENS", { bold: true, keepNext: true, alignment: "left", after: 70 }) + tabela(["Fase", "Item", "Horas"], [...fases].map(([k, h]) => [...k.split("|"), formatarHoras(h)]), [{ largura: 3055 }, { largura: 3900 }, { largura: 1500, alinhamento: "center", noWrap: true }]) : "") + (trabalhos.length ? p("PRINCIPAIS TRABALHOS REGISTRADOS", { bold: true, keepNext: true, alignment: "left", after: 60 }) + listaTrabalhos(trabalhos) : ""); }).join("");
  const revisoes = [...a.entregas].sort((x, y) => dataIso(x.data_entrega).localeCompare(dataIso(y.data_entrega))); const histRev = tabela(["Revisão", "Data", "Tipo", "Observação"], revisoes.map((r) => [r.revisao, formatarData(r.data_entrega), r.tipo_emissao === "revisao" ? "Revisão" : "Entrega inicial", r.observacoes || "—"]), [{ largura: 1100, alinhamento: "center", noWrap: true }, { largura: 1400, alinhamento: "center", noWrap: true }, { largura: 1600 }, { largura: 4355 }]);
  const equipe = a.colaboradores.map((nome) => { const rs = a.atividades.filter((r) => r.colaborador === nome), hs = rs.reduce((s, r) => s + horasAtividade(r), 0); return [nome, consolidarAtividades(rs).length, rs.length, formatarHoras(hs), a.horasTotais ? `${(hs / a.horasTotais * 100).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%` : "0%"]; });
  const pend = a.pendencias.length ? a.pendencias.map((x) => p(`⚠ ${x.mensagem}`, { alignment: "left", after: 60 })).join("") : p("Não foram identificadas pendências formais nas atividades desta entrega.", { firstLine: 567 }); const observacoes = texto(e.observacoes) ? p("Observações da entrega:", { bold: true, keepNext: true, alignment: "left" }) + p(e.observacoes, { firstLine: 567 }) : "";
  const anexo = gerarAnexoDetalhado(a.atividades, consolidarAtividades(a.atividades.filter((r) => horasAtividade(r) > 0)));
  const resultadoGantt = gerarGanttTabelaXml(montarGantt(a, ds));
  const gantt = normalizarCelulasGantt(resultadoGantt.xml);
  return { AAAA: `${a.obra.codigo} — ${a.obra.nome}`, ENTREGA: e.tipo_emissao === "revisao" ? "REVISÃO" : "ENTREGA INICIAL", REVISAO: e.revisao, DATA_ENTREGA: formatarData(e.data_entrega), PERIODO_RELATORIO: a.periodo.competencia, BBBB: apresentacao, CCCC: tabelaIdentificacao({ analise: a, entrega: e }, ids), DDDD: resumo, EEEE: disciplinas, FFFF: historico, GGGG: detalhes, HHHH: histRev, IIII: p(`Foram identificados ${a.colaboradores.length} colaborador(es), com ${formatarHoras(a.horasTotais)} registradas.`, { firstLine: 567 }) + tabela(["Colaborador", "Atividades", "Lançamentos", "Horas", "Participação"], equipe, [{ largura: 2855 }, { largura: 1300, alinhamento: "center" }, { largura: 1300, alinhamento: "center" }, { largura: 1500, alinhamento: "center", noWrap: true }, { largura: 1500, alinhamento: "center", noWrap: true }]), JJJJ: pend + observacoes, MMMM: conclusao(a, e), KKKK: anexo, LLLL: gantt };
}
function prepararTemplate(zip) { const arquivo = zip.file("word/document.xml"); let doc = arquivo.asText(); const textoVisivel = (trecho) => [...trecho.matchAll(/<w:t\b[^>]*>([\s\S]*?)<\/w:t>/g)].map((m) => m[1]).join("").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">"); doc = doc.replace(/<w:p\b[^>]*>[\s\S]*?<\/w:p>/g, (paragrafo) => { const visivel = textoVisivel(paragrafo); if (visivel.includes("[DATA_ENTREGA[")) return "<w:p><w:r><w:t>[DATA_ENTREGA]</w:t></w:r></w:p>"; const marcador = MARCADORES_OBRA.find((item) => visivel.includes(`[${item}]`)); return marcador ? `<w:p><w:r><w:t>[@${marcador}]</w:t></w:r></w:p>` : paragrafo; }); zip.file("word/document.xml", doc); }
function validarDocumento(zip) { const doc = zip.file("word/document.xml").asText(); const restantes = ["AAAA", "ENTREGA", "REVISAO", "DATA_ENTREGA", "PERIODO_RELATORIO", ...MARCADORES_OBRA].filter((m) => doc.includes(`[${m}]`) || doc.includes(`[@${m}]`)); if (restantes.length) throw Object.assign(new Error(`Marcadores não substituídos no documento: ${restantes.join(", ")}.`), { statusCode: 500 }); if (doc.includes("&lt;w:tbl")) throw Object.assign(new Error("Uma tabela OpenXML foi inserida como texto escapado."), { statusCode: 500 }); if ((doc.match(/<w:tbl>/g) || []).length < 2) throw Object.assign(new Error("Os anexos não contêm tabelas OpenXML reais."), { statusCode: 500 }); return true; }
function nomeArquivo(obra, revisao) { const slug = `${obra.codigo}-${obra.nome}-${revisao}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^A-Za-z0-9-]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, ""); return `relatorio-entrega-${slug}.docx`; }

async function carregarDadosObra(obraId, request, localizarObra, entregaId = "") {
  const obra = await localizarObra(obraId); if (!obra) throw Object.assign(new Error("Obra não encontrada."), { statusCode: 404 });
  const filtro = encodeURIComponent(obra.id);
  const [projetosFicha, atividadesDb, planner, entregas] = await Promise.all([
    request("obra_projetos", `?obra_id=eq.${filtro}&select=*&order=projeto.asc`),
    request("atividades_colaboradores", `?obra_id=eq.${filtro}&select=*&order=data_inicio.asc`),
    request("planner_checklists", `?obra_id=eq.${filtro}&select=*&order=data_inicio.asc`),
    request("obra_entregas", `?obra_id=eq.${filtro}&select=*&order=data_entrega.asc,criado_em.asc`)
  ]);
  const ids = (atividadesDb || []).map((a) => a.id).filter(Boolean); const classificacoes = [];
  for (let i = 0; i < ids.length; i += 75) classificacoes.push(...await request("atividade_classificacoes", `?atividade_id=in.(${ids.slice(i, i + 75).map(encodeURIComponent).join(",")})&select=*`));
  const porAtividade = new Map(); classificacoes.forEach((c) => { const lista = porAtividade.get(c.atividade_id) || []; lista.push(c); porAtividade.set(c.atividade_id, lista); });
  const atividades = (atividadesDb || []).map((a) => ({ ...a, classificacoes: porAtividade.get(a.id) || [] }));
  const entrega = entregaId ? (entregas || []).find((x) => String(x.id) === String(entregaId)) : null;
  if (entregaId && !entrega) throw Object.assign(new Error("Entrega não encontrada para a obra informada."), { statusCode: 404 });
  const projetosEntrega = entrega ? await request("obra_entrega_projetos", `?entrega_id=eq.${encodeURIComponent(entrega.id)}&select=*&order=projeto.asc`) : [];
  return { obra, projetosFicha: projetosFicha || [], atividades, planner: planner || [], entregas: entregas || [], projetosEntrega, entrega };
}

module.exports = { MARCADORES_OBRA, adicionarHyperlink, analisarObra, atividadeNoIntervalo, blocosGantt, carregarDadosObra, formatarData, mapearAtividade, montarXmlRelatorio, nomeArquivo, obterPeriodo, prepararTemplate, proximaRevisao, unirDisciplinas, validarDocumento, validarUrl };