const assert = require("assert");
const { chaveProjeto, completudeFicha, exigirAdmin, numeroOpcional, statusFicha, validarFicha } = require("./_obra-ficha");
assert.throws(() => exigirAdmin({ perfil: "colaborador" }), (error) => error.statusCode === 403);
assert.doesNotThrow(() => exigirAdmin({ perfil: "admin" }));
assert.equal(statusFicha(null), "cadastro_minimo");
assert.equal(statusFicha({ caracterizacao_nao_aplicavel: true }), "nao_aplicavel");
const caracteristica = { categoria_registro: "empreendimento", natureza: "publico", benchmark_status: "incluir" };
const tipologias = [{ segmento: "Saúde", tipologia: "Hospital", principal: true }];
assert.equal(statusFicha(caracteristica, tipologias, [{ intervencao: "Reforma" }]), "caracterizada");
assert.equal(statusFicha(caracteristica, tipologias, []), "parcial");
assert.equal(numeroOpcional(""), null); assert.equal(numeroOpcional("0"), 0);
assert.throws(() => numeroOpcional(-1), /não negativos/); assert.throws(() => numeroOpcional(1.5, true), /inteiros/);
assert.equal(chaveProjeto("Elétrico Baixa Tensão"), "eletrico-baixa-tensao");
const ficha = validarFicha({ categoriaRegistro: "empreendimento", natureza: "publico", areaIntervencao: "8700", areaExternaIntervencao: "", pavimentosAcima: "5", benchmarkStatus: "incluir", tipologias, intervencoes: ["Reforma", "Ampliação"], projetos: [{ projeto: "SPDA" }, { projeto: "SPDA" }] });
assert.equal(ficha.caracteristica.area_intervencao, 8700); assert.equal(ficha.caracteristica.area_externa_intervencao, null); assert.equal(ficha.projetos.length, 1); assert.equal(ficha.intervencoes.length, 2);
assert.throws(() => validarFicha({ benchmarkStatus: "excluir" }), /motivo/); assert.throws(() => validarFicha({ benchmarkStatus: "incluir", caracterizacaoNaoAplicavel: true }), /não pode integrar/);
assert.equal(completudeFicha(caracteristica, tipologias, [{ intervencao: "Reforma" }], [{ projeto: "SPDA" }]) > 0, true);
console.log("obra-ficha: testes concluídos");